FROM maven:3.8.4-jdk-11

COPY . /project/api-gateway
WORKDIR /project/api-gateway
#RUN apt install curl
#RUN curl -fsSL https://deb.nodesource.com/setup_16.13.1 | sudo -E bash -
#RUN apt-get install -y nodejs
RUN mvn clean package -e
