package com.sunknowledge.dme.rcm.repository;

import java.util.ArrayList;
import java.util.List;
import org.springframework.data.relational.core.sql.Column;
import org.springframework.data.relational.core.sql.Expression;
import org.springframework.data.relational.core.sql.Table;

public class DeliveryTicketSqlHelper {

    public static List<Expression> getColumns(Table table, String columnPrefix) {
        List<Expression> columns = new ArrayList<>();
        columns.add(Column.aliased("delivery_ticket_id", table, columnPrefix + "_delivery_ticket_id"));
        columns.add(Column.aliased("delivery_ticket_no", table, columnPrefix + "_delivery_ticket_no"));
        columns.add(Column.aliased("so_id", table, columnPrefix + "_so_id"));
        columns.add(Column.aliased("so_no", table, columnPrefix + "_so_no"));
        columns.add(Column.aliased("patient_first_name", table, columnPrefix + "_patient_first_name"));
        columns.add(Column.aliased("patient_middle_name", table, columnPrefix + "_patient_middle_name"));
        columns.add(Column.aliased("patient_last_name", table, columnPrefix + "_patient_last_name"));
        columns.add(Column.aliased("gender", table, columnPrefix + "_gender"));
        columns.add(Column.aliased("age_as_on_date", table, columnPrefix + "_age_as_on_date"));
        columns.add(Column.aliased("phone_1", table, columnPrefix + "_phone_1"));
        columns.add(Column.aliased("phone_2", table, columnPrefix + "_phone_2"));
        columns.add(Column.aliased("email", table, columnPrefix + "_email"));
        columns.add(Column.aliased("delivery_address_1", table, columnPrefix + "_delivery_address_1"));
        columns.add(Column.aliased("delivery_address_2", table, columnPrefix + "_delivery_address_2"));
        columns.add(Column.aliased("delivery_city", table, columnPrefix + "_delivery_city"));
        columns.add(Column.aliased("delivery_state", table, columnPrefix + "_delivery_state"));
        columns.add(Column.aliased("delivery_zip", table, columnPrefix + "_delivery_zip"));
        columns.add(Column.aliased("delivery_status", table, columnPrefix + "_delivery_status"));
        columns.add(Column.aliased("delivery_date", table, columnPrefix + "_delivery_date"));
        columns.add(Column.aliased("delivery_priority", table, columnPrefix + "_delivery_priority"));
        columns.add(Column.aliased("delivery_note", table, columnPrefix + "_delivery_note"));
        columns.add(Column.aliased("delivery_comment", table, columnPrefix + "_delivery_comment"));
        columns.add(Column.aliased("delivery_accepted_by", table, columnPrefix + "_delivery_accepted_by"));
        columns.add(Column.aliased("relationship_with_patient", table, columnPrefix + "_relationship_with_patient"));
        columns.add(Column.aliased("delivery_accepted_by_contact_no", table, columnPrefix + "_delivery_accepted_by_contact_no"));
        columns.add(Column.aliased("primary_insurer_name", table, columnPrefix + "_primary_insurer_name"));
        columns.add(Column.aliased("primary_insurer_policy_no", table, columnPrefix + "_primary_insurer_policy_no"));
        columns.add(Column.aliased("primary_insurer_patient_id_number", table, columnPrefix + "_primary_insurer_patient_id_number"));
        columns.add(Column.aliased("patient_id_no", table, columnPrefix + "_patient_id_no"));
        columns.add(Column.aliased("branch_address_line_1", table, columnPrefix + "_branch_address_line_1"));
        columns.add(Column.aliased("branch_address_line_2", table, columnPrefix + "_branch_address_line_2"));
        columns.add(Column.aliased("branch_city", table, columnPrefix + "_branch_city"));
        columns.add(Column.aliased("branch_state", table, columnPrefix + "_branch_state"));
        columns.add(Column.aliased("branch_zip_code", table, columnPrefix + "_branch_zip_code"));
        columns.add(Column.aliased("branch_contact_no_1", table, columnPrefix + "_branch_contact_no_1"));
        columns.add(Column.aliased("branch_contact_no_2", table, columnPrefix + "_branch_contact_no_2"));
        columns.add(Column.aliased("branch_npi", table, columnPrefix + "_branch_npi"));
        columns.add(Column.aliased("branch_ein", table, columnPrefix + "_branch_ein"));
        columns.add(Column.aliased("branch_fax", table, columnPrefix + "_branch_fax"));
        columns.add(Column.aliased("ordering_provider_first_name", table, columnPrefix + "_ordering_provider_first_name"));
        columns.add(Column.aliased("ordering_provider_middle_name", table, columnPrefix + "_ordering_provider_middle_name"));
        columns.add(Column.aliased("ordering_provider_last_name", table, columnPrefix + "_ordering_provider_last_name"));
        columns.add(Column.aliased("ordering_provider_npi", table, columnPrefix + "_ordering_provider_npi"));
        columns.add(Column.aliased("ordering_provider_address_line_1", table, columnPrefix + "_ordering_provider_address_line_1"));
        columns.add(Column.aliased("ordering_provider_address_line_2", table, columnPrefix + "_ordering_provider_address_line_2"));
        columns.add(Column.aliased("ordering_provider_city", table, columnPrefix + "_ordering_provider_city"));
        columns.add(Column.aliased("ordering_provider_state", table, columnPrefix + "_ordering_provider_state"));
        columns.add(Column.aliased("ordering_provider_zip", table, columnPrefix + "_ordering_provider_zip"));
        columns.add(Column.aliased("ordering_provider_phone_1", table, columnPrefix + "_ordering_provider_phone_1"));
        columns.add(Column.aliased("ordering_provider_phone_2", table, columnPrefix + "_ordering_provider_phone_2"));
        columns.add(Column.aliased("ordering_provider_fax", table, columnPrefix + "_ordering_provider_fax"));
        columns.add(Column.aliased("ordering_provider_email", table, columnPrefix + "_ordering_provider_email"));
        columns.add(Column.aliased("branch_name", table, columnPrefix + "_branch_name"));
        columns.add(Column.aliased("patient_branch_id", table, columnPrefix + "_patient_branch_id"));
        columns.add(Column.aliased("status", table, columnPrefix + "_status"));
        columns.add(Column.aliased("created_by_id", table, columnPrefix + "_created_by_id"));
        columns.add(Column.aliased("created_by_name", table, columnPrefix + "_created_by_name"));
        columns.add(Column.aliased("created_date", table, columnPrefix + "_created_date"));
        columns.add(Column.aliased("updated_by", table, columnPrefix + "_updated_by"));
        columns.add(Column.aliased("updated_by_name", table, columnPrefix + "_updated_by_name"));
        columns.add(Column.aliased("updated_date", table, columnPrefix + "_updated_date"));
        columns.add(Column.aliased("delivery_ticket_uuid", table, columnPrefix + "_delivery_ticket_uuid"));
        columns.add(Column.aliased("billing_address_line_1", table, columnPrefix + "_billing_address_line_1"));
        columns.add(Column.aliased("billing_address_line_2", table, columnPrefix + "_billing_address_line_2"));
        columns.add(Column.aliased("billing_city", table, columnPrefix + "_billing_city"));
        columns.add(Column.aliased("billing_state", table, columnPrefix + "_billing_state"));
        columns.add(Column.aliased("billing_zip", table, columnPrefix + "_billing_zip"));
        columns.add(Column.aliased("inventory_location_id", table, columnPrefix + "_inventory_location_id"));
        columns.add(Column.aliased("inventory_location_name", table, columnPrefix + "_inventory_location_name"));
        columns.add(Column.aliased("delivery_ticket_document_id", table, columnPrefix + "_delivery_ticket_document_id"));
        columns.add(Column.aliased("delivery_ticket_document_no", table, columnPrefix + "_delivery_ticket_document_no"));
        columns.add(Column.aliased("delivery_ticket_document_name", table, columnPrefix + "_delivery_ticket_document_name"));
        columns.add(Column.aliased("delivery_type", table, columnPrefix + "_delivery_type"));
        columns.add(Column.aliased("carrier_name", table, columnPrefix + "_carrier_name"));
        columns.add(Column.aliased("shipping_date", table, columnPrefix + "_shipping_date"));
        columns.add(Column.aliased("tracking_no", table, columnPrefix + "_tracking_no"));
        columns.add(Column.aliased("reference_no", table, columnPrefix + "_reference_no"));
        columns.add(Column.aliased("package_weight", table, columnPrefix + "_package_weight"));
        columns.add(Column.aliased("setup_method", table, columnPrefix + "_setup_method"));
        columns.add(Column.aliased("setup_technician_no", table, columnPrefix + "_setup_technician_no"));
        columns.add(Column.aliased("setup_technician_contact_no", table, columnPrefix + "_setup_technician_contact_no"));
        columns.add(Column.aliased("setup_technician_first_name", table, columnPrefix + "_setup_technician_first_name"));
        columns.add(Column.aliased("setup_technician_middle_name", table, columnPrefix + "_setup_technician_middle_name"));
        columns.add(Column.aliased("setup_technician_last_name", table, columnPrefix + "_setup_technician_last_name"));
        columns.add(Column.aliased("setup_date_time", table, columnPrefix + "_setup_date_time"));
        columns.add(Column.aliased("schedule_setup_date_time", table, columnPrefix + "_schedule_setup_date_time"));
        columns.add(Column.aliased("setup_comments", table, columnPrefix + "_setup_comments"));
        columns.add(Column.aliased("setup_status", table, columnPrefix + "_setup_status"));
        columns.add(Column.aliased("courier_package_accepted_by", table, columnPrefix + "_courier_package_accepted_by"));
        columns.add(Column.aliased("therapist_first_name", table, columnPrefix + "_therapist_first_name"));
        columns.add(Column.aliased("therapist_middle_name", table, columnPrefix + "_therapist_middle_name"));
        columns.add(Column.aliased("therapist_last_name", table, columnPrefix + "_therapist_last_name"));
        columns.add(Column.aliased("therapist_license_no", table, columnPrefix + "_therapist_license_no"));
        columns.add(Column.aliased("therapist_npi", table, columnPrefix + "_therapist_npi"));
        columns.add(Column.aliased("therapist_taxonomy_code", table, columnPrefix + "_therapist_taxonomy_code"));
        columns.add(Column.aliased("schedule_therapy_date", table, columnPrefix + "_schedule_therapy_date"));
        columns.add(Column.aliased("actual_therapy_date", table, columnPrefix + "_actual_therapy_date"));
        columns.add(Column.aliased("therapy_mode", table, columnPrefix + "_therapy_mode"));
        columns.add(Column.aliased("therapy_status", table, columnPrefix + "_therapy_status"));
        columns.add(Column.aliased("therapy_notes", table, columnPrefix + "_therapy_notes"));

        return columns;
    }
}
