package com.sunknowledge.dme.rcm.repository;

import java.util.ArrayList;
import java.util.List;
import org.springframework.data.relational.core.sql.Column;
import org.springframework.data.relational.core.sql.Expression;
import org.springframework.data.relational.core.sql.Table;

public class PatientDtoSqlHelper {

    public static List<Expression> getColumns(Table table, String columnPrefix) {
        List<Expression> columns = new ArrayList<>();
        columns.add(Column.aliased("patient_dto_id", table, columnPrefix + "_patient_dto_id"));
        columns.add(Column.aliased("patient_id", table, columnPrefix + "_patient_id"));
        columns.add(Column.aliased("patient_first_name", table, columnPrefix + "_patient_first_name"));
        columns.add(Column.aliased("patient_middle_name", table, columnPrefix + "_patient_middle_name"));
        columns.add(Column.aliased("patient_last_name", table, columnPrefix + "_patient_last_name"));
        columns.add(Column.aliased("dob", table, columnPrefix + "_dob"));
        columns.add(Column.aliased("gender", table, columnPrefix + "_gender"));
        columns.add(Column.aliased("ssn", table, columnPrefix + "_ssn"));
        columns.add(Column.aliased("tax_zone_id", table, columnPrefix + "_tax_zone_id"));
        columns.add(Column.aliased("tax_zone_name", table, columnPrefix + "_tax_zone_name"));
        columns.add(Column.aliased("tax_rate", table, columnPrefix + "_tax_rate"));
        columns.add(Column.aliased("patient_id_number", table, columnPrefix + "_patient_id_number"));
        columns.add(Column.aliased("address_line_1", table, columnPrefix + "_address_line_1"));
        columns.add(Column.aliased("address_line_2", table, columnPrefix + "_address_line_2"));
        columns.add(Column.aliased("city", table, columnPrefix + "_city"));
        columns.add(Column.aliased("state", table, columnPrefix + "_state"));
        columns.add(Column.aliased("country", table, columnPrefix + "_country"));
        columns.add(Column.aliased("zip", table, columnPrefix + "_zip"));
        columns.add(Column.aliased("contact_no_1", table, columnPrefix + "_contact_no_1"));
        columns.add(Column.aliased("contact_no_2", table, columnPrefix + "_contact_no_2"));
        columns.add(Column.aliased("fax", table, columnPrefix + "_fax"));
        columns.add(Column.aliased("efax", table, columnPrefix + "_efax"));
        columns.add(Column.aliased("email", table, columnPrefix + "_email"));
        columns.add(Column.aliased("branch_name", table, columnPrefix + "_branch_name"));
        columns.add(Column.aliased("billing_address_line_1", table, columnPrefix + "_billing_address_line_1"));
        columns.add(Column.aliased("billing_address_line_2", table, columnPrefix + "_billing_address_line_2"));
        columns.add(Column.aliased("billing_address_city", table, columnPrefix + "_billing_address_city"));
        columns.add(Column.aliased("billing_address_state", table, columnPrefix + "_billing_address_state"));
        columns.add(Column.aliased("billing_address_zip", table, columnPrefix + "_billing_address_zip"));
        columns.add(Column.aliased("caregiver_name", table, columnPrefix + "_caregiver_name"));
        columns.add(Column.aliased("caregiver_contact", table, columnPrefix + "_caregiver_contact"));
        columns.add(Column.aliased("caregiver_relatinship_patient", table, columnPrefix + "_caregiver_relatinship_patient"));
        columns.add(Column.aliased("primary_insurance_id", table, columnPrefix + "_primary_insurance_id"));
        columns.add(Column.aliased("primary_insurance_name", table, columnPrefix + "_primary_insurance_name"));
        columns.add(Column.aliased("primary_insurance_payer_id_no", table, columnPrefix + "_primary_insurance_payer_id_no"));
        columns.add(Column.aliased("primary_insurance_payer_contact_no", table, columnPrefix + "_primary_insurance_payer_contact_no"));
        columns.add(Column.aliased("primary_insurance_policy_num", table, columnPrefix + "_primary_insurance_policy_num"));
        columns.add(Column.aliased("primary_insurance_policy_group_num", table, columnPrefix + "_primary_insurance_policy_group_num"));
        columns.add(Column.aliased("primary_insurance_policy_group_id", table, columnPrefix + "_primary_insurance_policy_group_id"));
        columns.add(Column.aliased("primary_insurance_policy_start_date", table, columnPrefix + "_primary_insurance_policy_start_date"));
        columns.add(Column.aliased("primary_insurance_policy_end_date", table, columnPrefix + "_primary_insurance_policy_end_date"));
        columns.add(Column.aliased("primary_insurance_pay_percentage", table, columnPrefix + "_primary_insurance_pay_percentage"));
        columns.add(Column.aliased("primary_insurance_deductable_amt", table, columnPrefix + "_primary_insurance_deductable_amt"));
        columns.add(Column.aliased("secondary_insurance_id", table, columnPrefix + "_secondary_insurance_id"));
        columns.add(Column.aliased("secondary_insurance_name", table, columnPrefix + "_secondary_insurance_name"));
        columns.add(Column.aliased("secondary_insurance_payer_id_no", table, columnPrefix + "_secondary_insurance_payer_id_no"));
        columns.add(Column.aliased("secondary_insurance_payer_contact_no", table, columnPrefix + "_secondary_insurance_payer_contact_no"));
        columns.add(Column.aliased("secondary_insurance_policy_num", table, columnPrefix + "_secondary_insurance_policy_num"));
        columns.add(Column.aliased("secondary_insurance_policy_group_num", table, columnPrefix + "_secondary_insurance_policy_group_num"));
        columns.add(Column.aliased("secondary_insurance_policy_group_id", table, columnPrefix + "_secondary_insurance_policy_group_id"));
        columns.add(
            Column.aliased("secondary_insurance_policy_start_date", table, columnPrefix + "_secondary_insurance_policy_start_date")
        );
        columns.add(Column.aliased("secondary_insurance_policy_end_date", table, columnPrefix + "_secondary_insurance_policy_end_date"));
        columns.add(Column.aliased("secondary_insurance_pay_percentage", table, columnPrefix + "_secondary_insurance_pay_percentage"));
        columns.add(Column.aliased("secondary_insurance_deductable_amt", table, columnPrefix + "_secondary_insurance_deductable_amt"));
        columns.add(Column.aliased("tertiary_insurance_id", table, columnPrefix + "_tertiary_insurance_id"));
        columns.add(Column.aliased("tertiary_insurance_name", table, columnPrefix + "_tertiary_insurance_name"));
        columns.add(Column.aliased("tertiary_insurance_payer_id_no", table, columnPrefix + "_tertiary_insurance_payer_id_no"));
        columns.add(Column.aliased("tertiary_insurance_payer_contact_no", table, columnPrefix + "_tertiary_insurance_payer_contact_no"));
        columns.add(Column.aliased("tertiary_insurance_policy_num", table, columnPrefix + "_tertiary_insurance_policy_num"));
        columns.add(Column.aliased("tertiary_insurance_policy_group_num", table, columnPrefix + "_tertiary_insurance_policy_group_num"));
        columns.add(Column.aliased("tertiary_insurance_policy_group_id", table, columnPrefix + "_tertiary_insurance_policy_group_id"));
        columns.add(Column.aliased("tertiary_insurance_policy_start_date", table, columnPrefix + "_tertiary_insurance_policy_start_date"));
        columns.add(Column.aliased("tertiary_insurance_policy_end_date", table, columnPrefix + "_tertiary_insurance_policy_end_date"));
        columns.add(Column.aliased("tertiary_insurance_pay_percentage", table, columnPrefix + "_tertiary_insurance_pay_percentage"));
        columns.add(Column.aliased("tertiary_insurance_deductable_amt", table, columnPrefix + "_tertiary_insurance_deductable_amt"));
        columns.add(Column.aliased("relationship", table, columnPrefix + "_relationship"));
        columns.add(Column.aliased("insured_first_name", table, columnPrefix + "_insured_first_name"));
        columns.add(Column.aliased("insured_middle_name", table, columnPrefix + "_insured_middle_name"));
        columns.add(Column.aliased("insured_last_name", table, columnPrefix + "_insured_last_name"));
        columns.add(Column.aliased("insured_suffix", table, columnPrefix + "_insured_suffix"));
        columns.add(Column.aliased("insured_dob", table, columnPrefix + "_insured_dob"));
        columns.add(Column.aliased("insured_ssn", table, columnPrefix + "_insured_ssn"));
        columns.add(Column.aliased("insured_gender", table, columnPrefix + "_insured_gender"));
        columns.add(Column.aliased("primary_insurer_address_line_1", table, columnPrefix + "_primary_insurer_address_line_1"));
        columns.add(Column.aliased("primary_insurer_address_line_2", table, columnPrefix + "_primary_insurer_address_line_2"));
        columns.add(Column.aliased("primary_insurer_city", table, columnPrefix + "_primary_insurer_city"));
        columns.add(Column.aliased("primary_insurer_state", table, columnPrefix + "_primary_insurer_state"));
        columns.add(Column.aliased("primary_insurer_zip", table, columnPrefix + "_primary_insurer_zip"));
        columns.add(Column.aliased("primary_insurer_contact_1", table, columnPrefix + "_primary_insurer_contact_1"));
        columns.add(Column.aliased("primary_insurer_fax", table, columnPrefix + "_primary_insurer_fax"));
        columns.add(Column.aliased("always_crossover_status", table, columnPrefix + "_always_crossover_status"));
        columns.add(Column.aliased("primary_insurance_member_id", table, columnPrefix + "_primary_insurance_member_id"));
        columns.add(Column.aliased("secondary_insurance_member_id", table, columnPrefix + "_secondary_insurance_member_id"));
        columns.add(Column.aliased("tertiary_insurance_member_id", table, columnPrefix + "_tertiary_insurance_member_id"));
        columns.add(Column.aliased("patient_relationship_insured", table, columnPrefix + "_patient_relationship_insured"));
        columns.add(Column.aliased("patient_condition_employment", table, columnPrefix + "_patient_condition_employment"));
        columns.add(Column.aliased("patient_condition_auto_accident", table, columnPrefix + "_patient_condition_auto_accident"));
        columns.add(Column.aliased("patient_condition_other_accident", table, columnPrefix + "_patient_condition_other_accident"));
        columns.add(Column.aliased("insured_employer", table, columnPrefix + "_insured_employer"));
        columns.add(Column.aliased("workers_compensation_payer_id_number", table, columnPrefix + "_workers_compensation_payer_id_number"));
        columns.add(Column.aliased("workers_compensation_plan_name", table, columnPrefix + "_workers_compensation_plan_name"));
        columns.add(Column.aliased("workers_compensation_additional_dtls", table, columnPrefix + "_workers_compensation_additional_dtls"));
        columns.add(
            Column.aliased("workers_compensation_claim_filling_code", table, columnPrefix + "_workers_compensation_claim_filling_code")
        );
        columns.add(Column.aliased("workers_compensation_tpl_code", table, columnPrefix + "_workers_compensation_tpl_code"));
        columns.add(Column.aliased("workers_compensation_tpl_name", table, columnPrefix + "_workers_compensation_tpl_name"));
        columns.add(Column.aliased("wc_property_casualty_agency_claim_no", table, columnPrefix + "_wc_property_casualty_agency_claim_no"));
        columns.add(Column.aliased("wc_carrier_id", table, columnPrefix + "_wc_carrier_id"));
        columns.add(Column.aliased("employer_address_line_1", table, columnPrefix + "_employer_address_line_1"));
        columns.add(Column.aliased("employer_address_line_2", table, columnPrefix + "_employer_address_line_2"));
        columns.add(Column.aliased("employer_city", table, columnPrefix + "_employer_city"));
        columns.add(Column.aliased("employer_state", table, columnPrefix + "_employer_state"));
        columns.add(Column.aliased("employer_country", table, columnPrefix + "_employer_country"));
        columns.add(Column.aliased("employer_zip", table, columnPrefix + "_employer_zip"));
        columns.add(Column.aliased("employer_contact_no_1", table, columnPrefix + "_employer_contact_no_1"));
        columns.add(Column.aliased("employer_contact_no_2", table, columnPrefix + "_employer_contact_no_2"));
        columns.add(Column.aliased("employer_fax", table, columnPrefix + "_employer_fax"));
        columns.add(Column.aliased("employer_efax", table, columnPrefix + "_employer_efax"));
        columns.add(Column.aliased("employer_email", table, columnPrefix + "_employer_email"));
        columns.add(Column.aliased("employee_relationship", table, columnPrefix + "_employee_relationship"));
        columns.add(Column.aliased("height", table, columnPrefix + "_height"));
        columns.add(Column.aliased("weight", table, columnPrefix + "_weight"));
        columns.add(Column.aliased("functional_abilities", table, columnPrefix + "_functional_abilities"));
        columns.add(Column.aliased("infection_condition_status", table, columnPrefix + "_infection_condition_status"));
        columns.add(Column.aliased("diabetes_status", table, columnPrefix + "_diabetes_status"));
        columns.add(Column.aliased("diagnosis_code_type", table, columnPrefix + "_diagnosis_code_type"));
        columns.add(Column.aliased("icd_10_diagnosis_code_1", table, columnPrefix + "_icd_10_diagnosis_code_1"));
        columns.add(Column.aliased("icd_10_diagnosis_code_2", table, columnPrefix + "_icd_10_diagnosis_code_2"));
        columns.add(Column.aliased("icd_10_diagnosis_code_3", table, columnPrefix + "_icd_10_diagnosis_code_3"));
        columns.add(Column.aliased("icd_10_diagnosis_code_4", table, columnPrefix + "_icd_10_diagnosis_code_4"));
        columns.add(Column.aliased("icd_10_diagnosis_code_5", table, columnPrefix + "_icd_10_diagnosis_code_5"));
        columns.add(Column.aliased("icd_10_diagnosis_code_6", table, columnPrefix + "_icd_10_diagnosis_code_6"));
        columns.add(Column.aliased("icd_10_diagnosis_code_7", table, columnPrefix + "_icd_10_diagnosis_code_7"));
        columns.add(Column.aliased("icd_10_diagnosis_code_8", table, columnPrefix + "_icd_10_diagnosis_code_8"));
        columns.add(Column.aliased("icd_10_diagnosis_code_9", table, columnPrefix + "_icd_10_diagnosis_code_9"));
        columns.add(Column.aliased("icd_10_diagnosis_code_10", table, columnPrefix + "_icd_10_diagnosis_code_10"));
        columns.add(Column.aliased("icd_10_diagnosis_code_11", table, columnPrefix + "_icd_10_diagnosis_code_11"));
        columns.add(Column.aliased("icd_10_diagnosis_code_12", table, columnPrefix + "_icd_10_diagnosis_code_12"));
        columns.add(Column.aliased("doctor_first_name", table, columnPrefix + "_doctor_first_name"));
        columns.add(Column.aliased("doctor_middle_name", table, columnPrefix + "_doctor_middle_name"));
        columns.add(Column.aliased("doctor_last_name", table, columnPrefix + "_doctor_last_name"));
        columns.add(Column.aliased("doctor_name_suffix", table, columnPrefix + "_doctor_name_suffix"));
        columns.add(Column.aliased("doctor_address_line_1", table, columnPrefix + "_doctor_address_line_1"));
        columns.add(Column.aliased("doctor_address_line_2", table, columnPrefix + "_doctor_address_line_2"));
        columns.add(Column.aliased("doctor_address_city", table, columnPrefix + "_doctor_address_city"));
        columns.add(Column.aliased("doctor_address_state", table, columnPrefix + "_doctor_address_state"));
        columns.add(Column.aliased("doctor_address_zip", table, columnPrefix + "_doctor_address_zip"));
        columns.add(Column.aliased("doctor_contact_1", table, columnPrefix + "_doctor_contact_1"));
        columns.add(Column.aliased("doctor_contact_2", table, columnPrefix + "_doctor_contact_2"));
        columns.add(Column.aliased("doctor_fax", table, columnPrefix + "_doctor_fax"));
        columns.add(Column.aliased("doctor_npi_number", table, columnPrefix + "_doctor_npi_number"));
        columns.add(Column.aliased("doctor_gender", table, columnPrefix + "_doctor_gender"));
        columns.add(Column.aliased("doctor_taxonomy_code", table, columnPrefix + "_doctor_taxonomy_code"));
        columns.add(Column.aliased("doctor_taxonomy_description", table, columnPrefix + "_doctor_taxonomy_description"));
        columns.add(Column.aliased("doctor_practice_state", table, columnPrefix + "_doctor_practice_state"));
        columns.add(Column.aliased("doctor_license_number", table, columnPrefix + "_doctor_license_number"));
        columns.add(Column.aliased("status", table, columnPrefix + "_status"));
        columns.add(Column.aliased("created_date", table, columnPrefix + "_created_date"));
        columns.add(Column.aliased("created_by_id", table, columnPrefix + "_created_by_id"));
        columns.add(Column.aliased("created_by_name", table, columnPrefix + "_created_by_name"));
        columns.add(Column.aliased("updated_date", table, columnPrefix + "_updated_date"));
        columns.add(Column.aliased("updated_by_id", table, columnPrefix + "_updated_by_id"));
        columns.add(Column.aliased("updated_by_name", table, columnPrefix + "_updated_by_name"));
        columns.add(Column.aliased("patient_dto_uuid", table, columnPrefix + "_patient_dto_uuid"));
        columns.add(Column.aliased("secondary_insurer_address_line_1", table, columnPrefix + "_secondary_insurer_address_line_1"));
        columns.add(Column.aliased("secondary_insurer_address_line_2", table, columnPrefix + "_secondary_insurer_address_line_2"));
        columns.add(Column.aliased("secondary_insurer_city", table, columnPrefix + "_secondary_insurer_city"));
        columns.add(Column.aliased("secondary_insurer_state", table, columnPrefix + "_secondary_insurer_state"));
        columns.add(Column.aliased("secondary_insurer_zip", table, columnPrefix + "_secondary_insurer_zip"));
        columns.add(Column.aliased("secondary_insurer_contact_1", table, columnPrefix + "_secondary_insurer_contact_1"));
        columns.add(Column.aliased("secondary_insurer_fax", table, columnPrefix + "_secondary_insurer_fax"));
        columns.add(Column.aliased("tertiary_insurer_address_line_1", table, columnPrefix + "_tertiary_insurer_address_line_1"));
        columns.add(Column.aliased("tertiary_insurer_address_line_2", table, columnPrefix + "_tertiary_insurer_address_line_2"));
        columns.add(Column.aliased("tertiary_insurer_city", table, columnPrefix + "_tertiary_insurer_city"));
        columns.add(Column.aliased("tertiary_insurer_state", table, columnPrefix + "_tertiary_insurer_state"));
        columns.add(Column.aliased("tertiary_insurer_zip", table, columnPrefix + "_tertiary_insurer_zip"));
        columns.add(Column.aliased("tertiary_insurer_contact_1", table, columnPrefix + "_tertiary_insurer_contact_1"));
        columns.add(Column.aliased("tertiary_insurer_fax", table, columnPrefix + "_tertiary_insurer_fax"));

        return columns;
    }
}
