package com.sunknowledge.dme.rcm.documentutil;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.sunknowledge.dme.rcm.domain.DeliveryTicket;

import java.io.IOException;

public class HipaaNoticeDocsTableBuilder {
    public static PdfPTable createPatientRightsResponsibilitySubHeadingHipaa(String text) throws DocumentException, IOException
    {
        PdfPTable table = new PdfPTable(1);
        table.setWidthPercentage(100);
        table.setWidths(new float[]{ 1f });
        table.addCell(createTitleRowSmallTextHipaa(text));
        return table;
    }

    private static PdfPCell createTitleRowSmallTextHipaa(String text)
    {
        Font font = new Font(Font.FontFamily.HELVETICA, 8, Font.BOLD, BaseColor.BLACK);
        PdfPCell cell = new PdfPCell(new Phrase(text, font));
        //titleRowTextSmallSubTitle5Style(cell);
        cell.setHorizontalAlignment(Element.ALIGN_JUSTIFIED);
        cell.setPaddingTop(3f);
        //cell.setPaddingLeft(1f);
        cell.setPaddingBottom(3f);
        cell.setBackgroundColor(BaseColor.WHITE);
        cell.setBorderWidthBottom(0.1f);
        cell.setBorder(0);
        return cell;
    }

    public static PdfPTable createHipaaNoticeParagraphBoldAndNormal() throws DocumentException, IOException
    {
        PdfPTable table = new PdfPTable(1);
        table.setWidthPercentage(100);
        table.setWidths(new float[]{1f});
        table.addCell(createCellWithBodyLebelTextAsParagraphHipaa());
        return table;
    }

    private static PdfPCell createCellWithBodyLebelTextAsParagraphHipaa() {
        Font boldFont = new Font(Font.FontFamily.HELVETICA, 8, Font.BOLD, BaseColor.BLACK);
        Font normalFont = new Font(Font.FontFamily.HELVETICA, 8, Font.NORMAL, BaseColor.BLACK);

        Paragraph paragraph = new Paragraph();
        paragraph.add(new Phrase("If you have any questions about this Notice please contact our", normalFont));
        paragraph.add(new Phrase(" Privacy Contact", boldFont));
        paragraph.add(new Phrase(", [CONTACT], at [NUMBER]. This Notice describes how our practice and health care professionals, employees, volunteers, trainees and staff may use and disclose you medical information to carry out treatment, payment or health care operations and for other purposes that are described in this Notice. We understand that medical information about you and your health is personal and we are committed to protecting medical information about you. This Notice applies to all records of your care generated by this practice.\n", normalFont));

        PdfPCell cell = new PdfPCell(new Phrase(paragraph));
        titleRowTextSmallSubTitle5Style(cell);
        cell.setBorder(PdfPCell.NO_BORDER);
        cell.setHorizontalAlignment(Element.ALIGN_JUSTIFIED);
        return cell;
    }

    public static PdfPTable createHipaaNoticeParagraphNormal(String text) throws DocumentException, IOException
    {
        PdfPTable table = new PdfPTable(1);
        table.setWidthPercentage(100);
        table.setWidths(new float[]{1f});
        table.addCell(createCellWithBodyLebelTextAsParagraphNormalHipaa(text));
        return table;
    }

    private static PdfPCell createCellWithBodyLebelTextAsParagraphNormalHipaa(String text)
    {
        Font font = new Font(Font.FontFamily.HELVETICA, 8, Font.NORMAL, BaseColor.BLACK);
        PdfPCell cell = new PdfPCell(new Phrase(text, font));
        //titleRowTextSmallSubTitle5Style(cell);
        cell.setHorizontalAlignment(Element.ALIGN_JUSTIFIED);
        cell.setPaddingTop(3f);
        //cell.setPaddingLeft(1f);
        cell.setPaddingBottom(3f);
        cell.setBackgroundColor(BaseColor.WHITE);
        cell.setBorderWidthBottom(0.1f);
        cell.setBorder(0);
        return cell;
    }

    public static PdfPTable createHipaaNoticeListContents(String param1, String param2, String fontType) throws DocumentException, IOException
    {
        PdfPTable table = new PdfPTable(2);
        table.setWidthPercentage(100);
        table.setWidths(new float[]{ 0.03f, 1f });
        table.addCell(createCellWithBodyTableTextHipaaBullets(param1));
        table.addCell(createCellWithBodyTableTextHipaa(param2, fontType));

        return table;
    }

    public static PdfPTable createHipaaNoticeSubListContents(String param1, String param2, String fontType) throws DocumentException, IOException
    {
        PdfPTable table = new PdfPTable(3);
        table.setWidthPercentage(100);
        table.setWidths(new float[]{ 0.03f, 0.03f, 0.97f });
        table.addCell(createCellWithBodyTableTextHipaaBullets(" "));
        table.addCell(createCellWithBodyTableTextHipaaBullets(param1));
        table.addCell(createCellWithBodyTableTextHipaa(param2, fontType));
        return table;
    }

    public static PdfPTable createHipaaNoticeSubListContentsDivided(String param1, String param2, String fontType) throws DocumentException, IOException
    {
        PdfPTable table = new PdfPTable(3);
        table.setWidthPercentage(100);
        table.setWidths(new float[]{ 0.03f, 0.03f, 0.97f });
        table.addCell(createCellWithBodyTableTextHipaaBullets(" "));
        table.addCell(createCellWithBodyTableTextHipaaBullets(param1));
        table.addCell(createCellWithBodyTableTextHipaa(param2, fontType));
        table.setSpacingAfter(2);
        return table;
    }

    private static PdfPCell createCellWithBodyTableTextHipaaBullets(String text)
    {
        Font font = new Font(Font.FontFamily.HELVETICA, 8, Font.BOLD, BaseColor.BLACK);
        PdfPCell cell = new PdfPCell();
        Paragraph p = new Paragraph(text, font);
        p.setSpacingAfter(2);
        p.setAlignment(Element.ALIGN_LEFT);
        cell.addElement(p);
        titleRowTextSmallSubTitleTableContentStyle(cell);
        cell.setBorder(PdfPCell.NO_BORDER);
        cell.setPaddingBottom(3);
        return cell;
    }

    private static PdfPCell createCellWithBodyTableTextHipaa(String text, String fontType)
    {
        Font font = null;
        if(fontType.equals("boldAndUnderlined")){
            font = new Font(Font.FontFamily.HELVETICA, 8, Font.BOLD | Font.UNDERLINE, BaseColor.BLACK);
        }else if(fontType.equals("normal")){
            font = new Font(Font.FontFamily.HELVETICA, 8, Font.NORMAL, BaseColor.BLACK);
        }

        PdfPCell cell = new PdfPCell();
        Paragraph p = new Paragraph(text, font);
        p.setSpacingAfter(3);
        p.setAlignment(Element.ALIGN_JUSTIFIED);
        cell.addElement(p);
        titleRowTextSmallSubTitleTableContentStyle(cell);
        cell.setBorder(PdfPCell.NO_BORDER);
        return cell;
    }

    private static void titleRowTextSmallSubTitle5Style(PdfPCell cell)
    {
        cell.setHorizontalAlignment(Element.ALIGN_LEFT);
        cell.setPaddingTop(3f);
        cell.setPaddingLeft(1f);
        cell.setPaddingBottom(3f);
        cell.setBackgroundColor(BaseColor.WHITE);
        cell.setBorder(0);
        cell.setBorderWidthBottom(0.1f);
        cell.setBorderColorBottom(BaseColor.BLACK);
        cell.setBorderColorTop(BaseColor.BLACK);
    }

    private static void titleRowTextSmallSubTitleTableContentStyle(PdfPCell cell)
    {
        cell.setHorizontalAlignment(Element.ALIGN_LEFT);
        cell.setPaddingTop(3f);
        cell.setPaddingLeft(1f);
        cell.setPaddingBottom(3f);
        cell.setBackgroundColor(BaseColor.WHITE);
        cell.setBorder(0);
        cell.setPadding(0f);
//        cell.setBorderWidthBottom(0.1f);
        cell.setBorderColorBottom(BaseColor.BLACK);
        cell.setBorderColorTop(BaseColor.BLACK);
    }

    public static void populateDataInHipaaNoticeDocs(Document document, DeliveryTicket deliveryTicket) throws DocumentException, IOException {
        document.add(DeliveryDocumentTableBuilder.createPatientRightsResponsibilityMainBodyTitle(deliveryTicket));
        document.add(DeliveryDocumentTableBuilder.createPatientRightsResponsibilityMainHeading("HIPAA Notice of Privacy Practices (\"Notice\")"));
        document.add(createPatientRightsResponsibilitySubHeadingHipaa("THIS NOTICE DESCRIBES HOW INFORMATION ABOUT YOU MAY BE USED AND DISCLOSED AND HOW YOU CAN GET ACCESS TO THIS INFORMATION. IT FURTHER DETAILS HOW YOU OR YOUR PERSONAL REPRESENTATIVE MAY GAIN ACCESS TO THIS INFORMATION. PLEASE REVIEW CAREFULLY.\n"));
        document.add(createHipaaNoticeParagraphBoldAndNormal());
        document.add(createHipaaNoticeParagraphNormal("This Notice also describes your right to access and control your medical information. This information about you includes demographic information that may identify you and that relates to your past, present and future physical or mental health or condition and related health care services. Typically your medical information will include symptoms, examination and test results, diagnoses, treatment, and a plan for future care or treatment\n"));
        document.add(createHipaaNoticeParagraphNormal("We are required by law to protect the privacy of your medical information and to follow the terms of this Notice. We may change the terms of this Notice at anytime. The new Notice will then be effective for all medical information that we maintain at that time and thereafter. We will provide you with any revised Notice if you request a revised copy be sent to you in the mail or if you ask for one when you are in the office.\n"));
        document.add(createHipaaNoticeListContents(" I. ", "Uses and Disclosures of Protected Health Information", "boldAndUnderlined"));
        document.add(createHipaaNoticeListContents("    ", "Your medical information may be used and disclosed for purposes of treatment, payment and health care operations. The following are examples of different ways we use and disclose medical information. These are examples only.\n", "normal"));
        document.add(createHipaaNoticeSubListContents(" a. ", "Treatment", "boldAndUnderlined"));
        document.add(createHipaaNoticeSubListContents("    ", "We may use and disclose medical information about you to provide, coordinate, or manage your medical treatment or any related services. This includes the coordination or management of your health care with a third party that has already obtained your permission to have access to your medical information. For example, we could disclose your medical information to a home health agency that provides care to you. We may also disclose medical information to other physicians who may be treating you, such as a physician to whom you have been referred to ensure that the physician has the necessary information to diagnose or treat you. In addition, we may disclose your medical information to another physician or health care provider, such as a laboratory.\n", "normal"));

        document.add(createHipaaNoticeSubListContents(" b. ", "Payment", "boldAndUnderlined"));
        document.add(createHipaaNoticeSubListContents("    ", "We may use and disclose medical information about you to obtain payment for the treatment and services you receive from us. For example, we may need to provide your health insurance plan information about your treatment plan so that they can make a determination of eligibility or to obtain prior approval for planned treatment. For example, obtaining approval for a hospital stay may require that relevant medical information be disclosed to the health plan to obtain approval for the hospital admission.\n", "normal"));

        document.add(createHipaaNoticeSubListContents(" c. ", "Healthcare Operations", "boldAndUnderlined"));
        document.add(createHipaaNoticeSubListContentsDivided("    ", "We may use or disclose medical information about you in order to support the business activities of our practice. These activities include, but are not limited to, reviewing our treatment of you, employee performance reviews, training of medical students, licensing, marketing and fundraising activities and conducting or arranging for other business activities.", "normal"));
        document.add(createHipaaNoticeSubListContentsDivided("    ", "For example, we may use a sign-in sheet at the registration desk where you will be asked to sign your name and indicate your physician. We may call you by name in the waiting room when your physician is ready to see you. We may user or disclose your medical information to remind you of your next appointment.", "normal"));
        document.add(createHipaaNoticeSubListContentsDivided("    ", "We may share your medical information with third party \"business associates\" that perform activities on our behalf, such as billing or transcription for the practice. Whenever an arrangement between our office and a business associate involves that use or disclosure of your medical information, we will have a written contract that contains terms that asks the \"business associate\" to protect the privacy of your medical information.", "normal"));
        document.add(createHipaaNoticeSubListContentsDivided("    ", "We may use or disclose your medical information to provide you with information about treatment alternatives or other healthrelated benefits and services that may be of interest to you. We may also use and disclose your medical information for other marketing activities. For example, your name and address may be used to send you a newsletter about our practice and the services we offer. We may also send you information about products or services that we believe may be beneficial to you. You may contact our Privacy Contact to request that these materials not be sent to you.", "normal"));
        document.add(createHipaaNoticeSubListContentsDivided("    ", "We may use or disclose your demographic information and the dates that you received treatment from your physician, as necessary, in order to contact you for fundraising activities supported by our office. If you do not want to receive these materials, please contact our Privacy Contact to request that these fundraising materials not be sent to you.", "normal"));
        //document.add(DeliveryDocumentTableBuilder.createHipaaNoticeSubListContents("    ", "We may use or disclose medical information about you in order to support the business activities of our practice. These activities include, but are not limited to, reviewing our treatment of you, employee performance reviews, training of medical students, licensing, marketing and fundraising activities and conducting or arranging for other business activities.\n\nFor example, we may use a sign-in sheet at the registration desk where you will be asked to sign your name and indicate your physician. We may call you by name in the waiting room when your physician is ready to see you. We may user or disclose your medical information to remind you of your next appointment.\n\nWe may share your medical information with third party \"business associates\" that perform activities on our behalf, such as billing or transcription for the practice. Whenever an arrangement between our office and a business associate involves that use or disclosure of your medical information, we will have a written contract that contains terms that asks the \"business associate\" to protect the privacy of your medical information.\n\nWe may use or disclose your medical information to provide you with information about treatment alternatives or other healthrelated benefits and services that may be of interest to you. We may also use and disclose your medical information for other marketing activities. For example, your name and address may be used to send you a newsletter about our practice and the services we offer. We may also send you information about products or services that we believe may be beneficial to you. You may contact our Privacy Contact to request that these materials not be sent to you.\n\nWe may use or disclose your demographic information and the dates that you received treatment from your physician, as necessary, in order to contact you for fundraising activities supported by our office. If you do not want to receive these materials, please contact our Privacy Contact to request that these fundraising materials not be sent to you.\n", "normal"));

        document.add(createHipaaNoticeSubListContents(" d. ", "Healthcare Operations", "boldAndUnderlined"));
        document.add(createHipaaNoticeSubListContents("    ", "We may use and disclose medical information about you to provide, coordinate, or manage your medical treatment or any related services. This includes the coordination or management of your health care with a third party that has already obtained your permission to have access to your medical information. For example, we could disclose your medical information to a home health agency that provides care to you. We may also disclose medical information to other physicians who may be treating you, such as a physician to whom you have been referred to ensure that the physician has the necessary information to diagnose or treat you. In addition, we may disclose your medical information to another physician or health care provider, such as a laboratory.\n", "normal"));

        document.newPage(); // Goto new page
        document.add(createHipaaNoticeListContents(" II. ", "Other Permitted and Required Uses and Disclosures That May Be Made With Your Consent, Authorization or Opportunity to Object.\n", "boldAndUnderlined"));
        document.add(createHipaaNoticeListContents("    ", "We may use and disclose your medical information in the following instances. You have the opportunity to agree or object to the use or disclosure of all or part of your medical information. If you are not present or able to agree or object to the use or disclosure of the medical information, then your physician may, using professional judgment, determine whether the disclosure is in your best interest. In this case, only the medical information that is relevant to your health care will be disclosed.\n", "normal"));
        document.add(createHipaaNoticeSubListContents(" a. ", "Others Involved in Your Healthcare:", "boldAndUnderlined"));
        document.add(createHipaaNoticeSubListContents("    ", "Unless you object, we may disclose to a member of your family, a relative, or a close friend your medical information that directly related to that person's involvement in your health care. If you are unable to agree or object to such a disclosure, we may disclose such information if we determine that it is in your best interest based on our professional judgment. We may use or disclose medical information to notify or assist in notifying a family member or any other person that is responsible for your care of your location, general condition or death. Finally, we may use or disclose your medical information to an entity assisting in disaster relief efforts and to coordinate uses and disclosures to family or other individuals involved in your health care.\n", "normal"));
        document.add(createHipaaNoticeSubListContents(" b. ", "Emergencies:", "boldAndUnderlined"));
        document.add(createHipaaNoticeSubListContents("    ", "We may use or disclose your medical information for emergency treatment. If this happens, we shall try to obtain your consent as soon as reasonable after the delivery of treatment. If the practice is required by law to treat you and has attempted to obtain your consent but is unable to do so, the practice may still use or disclose your medical information to treat you.\n", "normal"));
        document.add(createHipaaNoticeSubListContents(" c. ", "Communication Barriers:", "boldAndUnderlined"));
        document.add(createHipaaNoticeSubListContents("    ", "We may use and disclose your medical information if the practice attempts to obtain consent from you but is unable to do so due to substantial communication barriers and, in our professional judgment, you intended to consent to use or disclose under the circumstances.\n", "normal"));

        document.add(createHipaaNoticeListContents(" III. ", "Other Permitted and Required Uses and Disclosures That May Be Made Without Your Consent, Authorization or Opportunity to Object.\n", "boldAndUnderlined"));
        document.add(createHipaaNoticeListContents("    ", "We may use or disclose your medical information in the following situations without your consent or authorization. These situations include:\n", "normal"));
        document.add(createHipaaNoticeSubListContents(" a. ", "Required By Law:", "boldAndUnderlined"));
        document.add(createHipaaNoticeSubListContents("    ", "We may use or disclose your medical information when federal, state or local law requires disclosure. You will be notified of any such uses or disclosure.", "normal"));
        document.add(createHipaaNoticeSubListContents(" b. ", "Public Health:", "boldAndUnderlined"));
        document.add(createHipaaNoticeSubListContents("    ", "We may disclose your medical information for public health activities and purposed to a public health authority that is permitted by law to collect or receive the information. This disclosure will be made for the purpose of controlling disease, injury or disability.", "normal"));
        document.add(createHipaaNoticeSubListContents(" c. ", "Communicable Diseases", "boldAndUnderlined"));
        document.add(createHipaaNoticeSubListContents("    ", "We may disclose your medical information, if authorized by law, to a person who may have been exposed to a communicable disease or may otherwise be at risk or contracting or spreading the disease or condition.", "normal"));
        document.add(createHipaaNoticeSubListContents(" d. ", "Health Oversight:", "boldAndUnderlined"));
        document.add(createHipaaNoticeSubListContents("    ", "We may disclose your medical information to a health oversight agency for activities authorized by law, such as audits, investigations, inspections and licensure. These activities are necessary for the government agencies to oversee the health care system, government benefit programs, other government regulatory programs and civil right laws.", "normal"));
        document.add(createHipaaNoticeSubListContents(" e. ", "Abuse or Neglect:", "boldAndUnderlined"));
        document.add(createHipaaNoticeSubListContents("    ", " Abuse or Neglect: We may disclose your medical information to a public health authority that is authorized by law to receive reports of child abuse or neglect. In addition, we may disclose your medical information to the governmental entity authorized to receive such information if we believe that you have been a victim of abuse, neglect or domestic violence as is consistent with the requirements of applicable federal and state laws.", "normal"));
        document.add(createHipaaNoticeSubListContents(" f. ", "Food and Drug Administration:", "boldAndUnderlined"));
        document.add(createHipaaNoticeSubListContents("    ", "We may disclose your medical information to a person or company required by the Food and Drug Administration to report adverse events, products defects or problems, biologic product deviations track products; to enable product recalls; to make repairs or replacements, or to conduct post marketing surveillance, as required.", "normal"));
        document.add(createHipaaNoticeSubListContents(" g. ", "Legal Proceedings:", "boldAndUnderlined"));
        document.add(createHipaaNoticeSubListContents("    ", "We may disclose medical information it the course of any judicial or administrative proceeding, when required by a court order or administrative tribunal, and in certain conditions in response to a subpoena, discovery request or other lawful process.", "normal"));
        document.add(createHipaaNoticeSubListContents(" h. ", "Legal Proceedings:", "boldAndUnderlined"));
        document.add(createHipaaNoticeSubListContents("    ", "We may disclose medical information, so long as applicable legal requirements are met, for law enforcement purposes. These law enforcement purposes include: (i) responding to a court order, subpoena, warrant, summons or otherwise required by law; (ii) identifying or locating a suspect, fugitive, material witness or missing person; (iii) pertaining to victims of a crime; (iv) suspecting that death has occurred as a result of criminal conduct; (v) in the event that a crime occurs on the premises of the practice; and (vi) responding to a medical emergent (not on the Practice’s premises) and it is likely that a crime has occurred.", "normal"));
        document.newPage(); // Goto new page
        document.add(createHipaaNoticeSubListContents(" i. ", "Coroners, Funeral Directors, and Organ Donors:", "boldAndUnderlined"));
        document.add(createHipaaNoticeSubListContents("    ", "We may disclose medical information to a coroner or medical examiner for identification purposes, determining cause of death or for the coroner or medical examiner to perform other duties authorized by law. We may also disclose medical information to funeral directors as necessary to carry out their duties.", "normal"));
        document.add(createHipaaNoticeSubListContents(" j. ", "Research:", "boldAndUnderlined"));
        document.add(createHipaaNoticeSubListContents("    ", "We may use and disclose your PHI for research purposes in certain limited circumstances. We will obtain your written authorization to use your PHI for research purposes except when an Internal Review Board (“IRB”) or Privacy Board has determined that the waiver of your authorization satisfies the following: (i) the use or disclosure involves no more than a minimal risk to your privacy based on the following: (A) an adequate plan to protect the identifiers from improper use and disclosure; (B) an adequate plan to destroy the identifiers at the earliest opportunity consistent with the research (unless there is a health or research justification for retaining the identifiers or such retention is otherwise required by law); and (C) adequate, written assurances that the PHI will not be re-used or disclosed to any other person or entity (except as required by law) for authorized oversight of the research study, or for other research for which the use or disclosure would otherwise be permitted; (ii) the research could not practicably be conducted without the waiver; and (iii) the research could not practicably be conducted without access to and use of the PHI.", "normal"));
        document.add(createHipaaNoticeSubListContents(" k. ", "Criminal Activity:", "boldAndUnderlined"));
        document.add(createHipaaNoticeSubListContents("    ", "Consistent with applicable federal and state laws, we may disclose your medical information, if we believe that the use or disclosure is necessary to prevent or lessen a serious and imminent threat to the health or safety of a person of the public. We may also disclose medical information if it is necessary for law enforcement authorities to identify or apprehend an individual.", "normal"));
        document.add(createHipaaNoticeSubListContents(" l. ", "Organ and Tissue Donation:", "boldAndUnderlined"));
        document.add(createHipaaNoticeSubListContents("    ", "If you are an organ donor, we may release medical information to organizations that handle organ procurement or organ, eye or tissue transplantation or to an organ donation bank, as necessary to facilitate organ or tissue donation and transplantation.", "normal"));
        document.add(createHipaaNoticeSubListContents(" m. ", "Military Activity and National Security:", "boldAndUnderlined"));
        document.add(createHipaaNoticeSubListContents("    ", "If you are a member of the armed forces, we may use or disclose medical information, (i) as required by military command authorities; (ii) for the purpose of determining by the Department of Veteran Affairs of your eligibility for benefits; or (iii) for foreign military personnel to the appropriate foreign military authority. We may also disclose your medial information to authorized federal officials for conducting national security and intelligence activities, including for the protective services to thePresident or others legally authorized.", "normal"));
        document.add(createHipaaNoticeSubListContents(" n. ", "Worker's Compensation:", "boldAndUnderlined"));
        document.add(createHipaaNoticeSubListContents("    ", "We may disclose your medical information as authorized to comply with workers' compensation laws and other similar programs that provide benefits for work-related injuries or illness.", "normal"));
        document.add(createHipaaNoticeSubListContents(" o. ", "Inmates:", "boldAndUnderlined"));
        document.add(createHipaaNoticeSubListContents("    ", "We may use or disclose your medical information if you are an inmate or a correctional facility and our practice created or received your health information in the course of providing care to you.", "normal"));
        document.add(createHipaaNoticeSubListContents(" p. ", "Required Uses and Disclosures:", "boldAndUnderlined"));
        document.add(createHipaaNoticeSubListContents("    ", "Under the law, we must make disclosures to you and when required by the Secretary of the Department of Health and Human Services to investigate or determine our compliance with the requirements of Section 164.500, et seq. seq.", "normal"));

        document.add(createHipaaNoticeListContents(" IV. ", "The Following Is a Statement of Your Rights with Respect to Your Medical Information and a Brief Description of How You May Exercise These Rights.\n", "boldAndUnderlined"));
        document.add(createHipaaNoticeSubListContents(" a. ", "You have the right to inspect and copy your medical information.", "boldAndUnderlined"));
        document.add(createHipaaNoticeSubListContentsDivided("    ", "This means you may inspect and obtain a copy of medical information about you that has originated in our practice. We may charge you a reasonable fee for copying and mailing records. To the extent we maintain any portion of your PHI in electronic format, you have the right to receive such PHI from us in an electronic format. We will charge no more than actual labor cost to provide you electronic versions of your PHI that we maintain in electronic format", "normal"));
        document.add(createHipaaNoticeSubListContentsDivided("    ", "After you have made a written request to our Privacy Contact at the following address: [ADDRESS], we will have thirty (30) days to satisfy your request. If we deny your request to inspect or copy your medical information, we will provide you with a written explanation of the denial. You may not have a right to inspect or copy psychotherapy notes. In some circumstances, you may have a right to have the decision to deny you access reviewed. Please contact the Privacy Contact if you have any questions about access to your medical record.", "normal"));
        document.add(createHipaaNoticeSubListContents(" b. ", "You have the right to request a restriction of your medical information.", "boldAndUnderlined"));
        document.add(createHipaaNoticeSubListContents("    ", "You may ask us not to use or disclose part of your medical information for the purposes of treatment, payment or healthcare operations. You may also request that part of your medical information not be disclosed to family members or friends who may be involved in your care or for notification purposes as described in this Notice. You must state in writing the specific restriction requested and to whom you want the restriction to apply. You have the right to restrict information sent to your health plan or insurer for products or services that you paid for solely out-of-pocket and for which no claim was made to your health plan or insurer.", "normal"));
        document.newPage(); // Goto new page
        document.add(createHipaaNoticeSubListContents(" c. ", "We are not required to agree to your request.", "boldAndUnderlined"));
        document.add(createHipaaNoticeSubListContents("    ", "If we believe it is in your best interest to permit use and disclosure of your medical information, you medical information will not be restricted; provided, however, we must agree to your request to restrict disclosure of your medical information if: (i) the disclosure is for the purpose of carrying out payment or health care operations and is not otherwise required by law; and (ii) the information pertains solely to a health care item or service for which you (and not your health plan) have paid us in full. If we do agree to the requested restriction, we may not use or disclose your medical information in violation of that restriction unless it is needed to provide emergency treatment. Your written request must be specific as to what information you want to limit and to whom you want the limits to apply. The request should be sent, in writing, to our Privacy Contact.", "normal"));
        document.add(createHipaaNoticeSubListContents(" d. ", "You have the right to request to receive confidential communications from us at a location other than your primary address.", "boldAndUnderlined"));
        document.add(createHipaaNoticeSubListContents("    ", "We will try to accommodate reasonable requests. Please make this request in writing to our Privacy Contact", "normal"));
        document.add(createHipaaNoticeSubListContents(" e. ", "You may have the right to have us amend your medical information.", "boldAndUnderlined"));
        document.add(createHipaaNoticeSubListContents("    ", "If you feel that medical information we have about you is incorrect or incomplete, you may request we amend the information. If you wish to request an amendment to your medical information, please contact our Privacy Contact, in writing to request our form Request to Amend Health Information. In certain cases, we may deny your request for an amendment. If we deny your request for amendment, you have the right to file a statement of disagreement with us.", "normal"));
        document.add(createHipaaNoticeSubListContents(" f. ", "You have the right to receive an accounting of disclosures we have made, if any, of your medical information.", "boldAndUnderlined"));
        document.add(createHipaaNoticeSubListContents("    ", "This applies to disclosures for purposes other than treatment, payment or healthcare operations as described in this Notice. If excludes disclosures we may have made to you, family members or friends involved in your care, or for notification purposes. To receive information regarding disclosures made for a specific time period no longer than six (6) years and after April 14, 2003, please submit your request in writing to our Privacy Contact. We will notify you in writing of the cost involved in preparing this list. To the extent we maintain your PHI in electronic format, you may request an accounting of all electronic disclosures of your PHI for treatment, payment, or healthcare operations for the preceding three (3) years prior to such request.", "normal"));
        document.add(createHipaaNoticeSubListContents(" g. ", "Uses and Disclosures of Protected Health Information Based Upon Your Written Authorization.", "boldAndUnderlined"));
        document.add(createHipaaNoticeSubListContents("    ", "Other uses and disclosures of your medical information not covered by this Notice or required by law will be made only with your written authorization. For example, most uses and disclosures of psychotherapy notes; PHI for marketing purposes; that constitute a sale of PHI and other than those described in this Notice, require authorization. You may revoke this authorization at any time, except to the extent that our practice has taken an action in reliance on the use or disclosure indicated in the prior authorization", "normal"));
        document.add(createHipaaNoticeSubListContents(" h. ", "Right to be Notified of a Breach", "boldAndUnderlined"));
        document.add(createHipaaNoticeSubListContents("    ", "You have the right to be notified in the event that our practice (or a Business Associate or ours) discovers a breach of unsecured protected health information.", "normal"));
        document.add(createHipaaNoticeSubListContents(" i. ", "Complaints:", "boldAndUnderlined"));
        document.add(createHipaaNoticeSubListContents("    ", "You may complain to us or to the Secretary of Health and Human Services if you believe your privacy rights have been violated by us. You may file a complaint with us by notifying our Privacy Contact, in writing. We will not retaliate against you for filing a complaint.", "normal"));
        document.add(createHipaaNoticeParagraphNormal("By signing this form, you acknowledge receiving this Notice and that you were afforded an opportunity to ask questions related to the content herein.\n"));
        //document.add(DeliveryDocumentTableBuilder.createPatientRightsResponsibilitySubHeading("As an individual receiving home care services, let it be known that you have the following responsibilities:"));
        //document.add(DeliveryDocumentTableBuilder.createPatientRightsResponsibilitySubContentsSecond());

        //document.add(new Paragraph("\n"));

        // Move to the next page
        //document.newPage();
    }
}
