package com.sunknowledge.changehealthcare.application.utils;

public final class ApplicationConstants {
	private ApplicationConstants() {
	}

	/*
	 * ===============================CHANGE HEALTHCARE SERVICE=================================
	 */
	public static final String CLIENT_ID = "9Motr81e6lSmv7bCt21fnhSiX7Qe65ZL";
	public static final String CLIENT_SECRET = "7JmEskqxfeI5GHFr";
	public static final String TOKEN_GENERATION_URL = "https://sandbox.apigw.changehealthcare.com/apip/auth/v2/token";
	public static final String ELLIGIBILITY_HEALTHCHECK_URL = "https://sandbox.apigw.changehealthcare.com/medicalnetwork/eligibility/v3/healthcheck";
	public static final String ELLIGIBILITY_URL = "https://sandbox.apigw.changehealthcare.com/medicalnetwork/eligibility/v3/";
	public static final String CLAIMSTATUS_URL = "https://sandbox.apigw.changehealthcare.com/medicalnetwork/claimstatus/v2";
	public static final String CLAIMSTATUS_HEALTHCHECK_URL = "https://sandbox.apigw.changehealthcare.com/medicalnetwork/claimstatus/v2/healthcheck";
	public static final String ATTACHMENT_HEALTHCHECK_URL = "https://sandbox.apigw.changehealthcare.com/medicalnetwork/attachments/submission/v1/healthcheck";
	public static final String ATTACHMENT_SUBMISSION_URL = "https://sandbox.apigw.changehealthcare.com/medicalnetwork/attachments/submission/v1/uploads";
	public static final String ATTACHMENT_SUBMISSION_URL = "https://sandbox.apis.changehealthcare.com/medicalnetwork/attachments/submission/v1/uploads";
	public static final String ATTACHMENT_SUBMISSION_JSON_STRING = "{\r\n"
			+ "  \"controlNumber\": \"000000001\",\r\n"
			+ "  \"tradingPartnerServiceId\": \"9496\",\r\n"
			+ "  \"tradingPartnerName\":\"Happy Payers of Washington State\",\r\n"
			+ "  \"payerAddress\": {\r\n"
			+ "      \"address1\": \"123 address1\",\r\n"
			+ "      \"city\": \"city1\",\r\n"
			+ "      \"state\": \"wa\",\r\n"
			+ "      \"postalCode\": \"981010000\"\r\n"
			+ "    },\r\n"
			+ "  \"submitter\": {\r\n"
			+ "    \"organizationName\": \"REGIONAL PPO NETWORK\",\r\n"
			+ "    \"contactInformation\": {\r\n"
			+ "      \"name\": \"SUBMITTER CONTACT INFO\",\r\n"
			+ "      \"phoneNumber\": \"123456789\"\r\n"
			+ "    }\r\n"
			+ "  },\r\n"
			+ "  \"receiver\": {\r\n"
			+ "    \"organizationName\": \"EXTRA HEALTHY INSURANCE\"\r\n"
			+ "  },\r\n"
			+ "  \"provider\": {\r\n"
			+ "    \"providerType\": \"BillingProvider\",\r\n"
			+ "    \"npi\": \"1760854442\",\r\n"
			+ "    \"employerId\": \"123456789\",\r\n"
			+ "    \"organizationName\": \"HAPPY DOCTORS GROUPPRACTICE\",\r\n"
			+ "    \"address\": {\r\n"
			+ "      \"address1\": \"000 address1\",\r\n"
			+ "      \"city\": \"city2\",\r\n"
			+ "      \"state\": \"tn\",\r\n"
			+ "      \"postalCode\": \"372030000\"\r\n"
			+ "    },\r\n"
			+ "    \"contactInformation\": {\r\n"
			+ "      \"name\": \"janetwo doetwo\",\r\n"
			+ "      \"phoneNumber\": \"0000000001\"\r\n"
			+ "    }\r\n"
			+ "  },\r\n"
			+ "   \"subscriber\": {\r\n"
			+ "        \"memberId\": \"0000000000\",\r\n"
			+ "		\"paymentResponsibilityLevelCode\": \"P\",\r\n"
			+ "        \"firstName\": \"johnOne\",\r\n"
			+ "        \"lastName\": \"doeOne\",\r\n"
			+ "        \"gender\": \"M\",\r\n"
			+ "        \"dateOfBirth\": \"18800102\",\r\n"
			+ "        \"ssn\": \"555443333\",\r\n"
			+ "        \"idCard\": \"card123\",\r\n"
			+ "		\"address\": {\r\n"
			+ "			\"address1\": \"000 address1\",\r\n"
			+ "			\"city\": \"city2\",\r\n"
			+ "			\"state\": \"tn\",\r\n"
			+ "			\"postalCode\": \"372030000\"\r\n"
			+ "		}\r\n"
			+ "    },\r\n"
			+ "  \"claimInformation\": {\r\n"
			+ "    \"claimFilingCode\": \"CI\",\r\n"
			+ "    \"patientControlNumber\": \"12345\",\r\n"
			+ "    \"beginClaimServiceDate\": \"20050514\",\r\n"
			+ "    \"endClaimServiceDate\": \"20050614\",\r\n"
			+ "    \"claimChargeAmount\": \"28.75\",\r\n"
			+ "    \"placeOfServiceCode\": \"11\",\r\n"
			+ "    \"claimFrequencyCode\": \"1\",\r\n"
			+ "    \"signatureIndicator\": \"Y\",\r\n"
			+ "    \"planParticipationCode\": \"A\",\r\n"
			+ "    \"benefitsAssignmentCertificationIndicator\": \"Y\",\r\n"
			+ "    \"releaseInformationCode\": \"Y\",\r\n"
			+ "    \"claimSupplementalInformation\": {\r\n"
			+ "      \"repricedClaimNumber\": \"00001\",\r\n"
			+ "      \"claimNumber\": \"12345\"\r\n"
			+ "    },\r\n"
			+ "    \"healthCareCodeInformation\": [{\r\n"
			+ "      \"diagnosisTypeCode\": \"BK\",\r\n"
			+ "      \"diagnosisCode\": \"496\"\r\n"
			+ "    },{\r\n"
			+ "      \"diagnosisTypeCode\": \"BF\",\r\n"
			+ "      \"diagnosisCode\": \"25000\"\r\n"
			+ "    }],\r\n"
			+ "    \"serviceFacilityLocation\": {\r\n"
			+ "      \"organizationName\": \"HAPPY DOCTORS GROUP\",\r\n"
			+ "      \"address\": {\r\n"
			+ "        \"address1\": \"000 address1\",\r\n"
			+ "        \"city\": \"city2\",\r\n"
			+ "        \"state\": \"tn\",\r\n"
			+ "        \"postalCode\": \"372030000\"\r\n"
			+ "      }\r\n"
			+ "      },\r\n"
			+ "    \"serviceLines\":[ {\r\n"
			+ "      \"serviceDate\": \"20050514\",\r\n"
			+ "      \"payerClaimControlNumber\": \"123456789\",\r\n"
			+ "      \"serviceLineDateInformation\" : {\r\n"
			+ "          \"submissionDate\" : \"20050514\"\r\n"
			+ "      },\r\n"
			+ "      \"professionalService\": {\r\n"
			+ "        \"procedureIdentifier\": \"HC\",\r\n"
			+ "        \"lineItemChargeAmount\": \"25\",\r\n"
			+ "        \"procedureCode\": \"E0570\",\r\n"
			+ "        \"measurementUnit\": \"UN\",\r\n"
			+ "        \"serviceUnitCount\": \"1\",\r\n"
			+ "        \"compositeDiagnosisCodePointers\": {\r\n"
			+ "          \"diagnosisCodePointers\": [\"1\",\"2\"]\r\n"
			+ "        }\r\n"
			+ "      },\r\n"
			+ "      \"attachmentDetails\": {\r\n"
			+ "        \"name\": \"IMG2.png\",\r\n"
			+ "        \"name\": \"IMG3.png\"\r\n"
			+ "      }\r\n"
			+ "      }\r\n"
			+ "    ]\r\n"
			+ "\r\n"
			+ "  }\r\n"
			+ "}";
	public static final String CLAIMSTATUS_JSON_STRING = "{\r\n"
			+ "                \"controlNumber\": \"000000001\",\r\n"
			+ "                \"tradingPartnerServiceId\": \"serviceId\",\r\n"
			+ "                \"providers\": [{\r\n"
			+ "                                \"organizationName\": \"TestProvider\",\r\n"
			+ "                                \"taxId\": \"0123456789\",\r\n"
			+ "                                \"providerType\": \"BillingProvider\",\r\n"
			+ "								\"firstName\": \"John\",\r\n"
			+ "								\"lastName\": \"Wick\",\r\n"
			+ "								\"npi\": \"1760854442\",\r\n"
			+ "								\"spn\": \"1760854442\",\r\n"
			+ "								\"tin\": \"1760854442\",\r\n"
			+ "								\"etin\": \"1760854442\"\r\n"
			+ "                }],\r\n"
			+ "                \"subscriber\": {\r\n"
			+ "                                \"memberId\": \"0000000000\",\r\n"
			+ "                                \"firstName\": \"johnone\",\r\n"
			+ "                                \"lastName\": \"doeone\",\r\n"
			+ "                                \"gender\": \"M\",\r\n"
			+ "                                \"dateOfBirth\": \"18800102\",\r\n"
			+ "                                \"groupNumber\": \"0000000000\"\r\n"
			+ "                },\r\n"
			+ "                \"dependent\": {\r\n"
			+ "                                \"firstName\": \"janeone\",\r\n"
			+ "                                \"lastName\": \"doeone\",\r\n"
			+ "                                \"gender\": \"F\",\r\n"
			+ "                                \"dateOfBirth\": \"18800101\",\r\n"
			+ "                                \"groupNumber\": \"0000000000\"\r\n"
			+ "                },\r\n"
			+ "                \"encounter\": {\r\n"
			+ "                                \"beginningDateOfService\": \"20100101\",\r\n"
			+ "                                \"endDateOfService\": \"20100102\",\r\n"
			+ "                                \"trackingNumber\": \"1\",\r\n"
			+ "								\"tradingPartnerClaimNumber\": \"1\",\r\n"
			+ "								\"locationIdentifier\": \"1760854442\",\r\n"
			+ "								\"billingType\": \"1760854442\",\r\n"
			+ "								\"patientAccountNumber\": \"1760854442\",\r\n"
			+ "								\"pharmacyPrescriptionNumber\": \"1760854442\",\r\n"
			+ "								\"clearingHouseClaimNumber\": \"1\",\r\n"
			+ "								\"submittedAmount\": \"1\"\r\n"
			+ "                },\r\n"
			+ "				\"serviceLineInformation\": {\r\n"
			+ "					\"procedureModifiers\": [\r\n"
			+ "						\"PM\"\r\n"
			+ "					],\r\n"
			+ "					\"productOrServiceIDQualifier\": \"AD\",\r\n"
			+ "					\"procedureCode\": \"PC\",\r\n"
			+ "					\"lineItemChargeAmount\": \"200\",\r\n"
			+ "					\"revenueCode\": \"C\",\r\n"
			+ "					\"unitsOfServiceCount\": \"1\",\r\n"
			+ "					\"lineItemControlNumber\": \"2221555500405\",\r\n"
			+ "					\"serviceLineDate\": \"18800101\",\r\n"
			+ "					\"serviceLineEndDate\": \"18800101\"\r\n"
			+ "				}\r\n"
			+ "}";
	public static final String ELLIGIBILITY_JSON_STRING = "{\r\n" + "  \"tradingPartnerServiceId\": \"000015\",\r\n"
			+ "  \"controlNumber\": \"111234567\",\r\n" + "  \"submitterTransactionIdentifier\": \"12321\",\r\n"
			+ "  \"tradingPartnerName\": \"fvdfvds\",\r\n" + "  \"portalUsername\": \"sdvsdv\",\r\n"
			+ "  \"portalPassword\": \"uygbugu\",\r\n" + "  \"subscriberTraceNumber\": {\r\n"
			+ "      \"traceTypeCode\": \"A\",\r\n" + "      \"traceType\": \"B\",\r\n"
			+ "      \"referenceIdentification\": \"C\",\r\n" + "      \"originatingCompanyIdentifier\": \"D\"\r\n"
			+ "  },\r\n" + "  \"subscriber\": {\r\n" + "    \"memberId\": \"0000000000\",\r\n"
			+ "    \"firstName\": \"johnOne\",\r\n" + "    \"lastName\": \"doeOne\",\r\n"
			+ "    \"suffix\": \"Mr\",\r\n" + "    \"groupNumber\": \"1111111111\",\r\n"
			+ "    \"idCard\": \"card123\",\r\n" + "    \"ssn\": \"555443333\",\r\n"
			+ "    \"caseNumber\": \"qwerty\",\r\n" + "    \"medicaidRecipientIdentificationNumber\": \"asdfg\",\r\n"
			+ "    \"planNumber\": \"jhgh\",\r\n" + "    \"policyNumber\": \"svsdvsv\",\r\n"
			+ "    \"memberIdentificationNumber\": \"sczxczxc\",\r\n" + "    \"contractNumber\": \"zxzxzx\",\r\n"
			+ "    \"medicalRecordIdentificationNumber\": \"bvbvbvb\",\r\n"
			+ "    \"patientAccountNumber\": \"uj\",\r\n" + "    \"healthInsuranceClaimNumber\": \"pl\",\r\n"
			+ "    \"identificationCardSerialNumber\": \"uhniuh\",\r\n"
			+ "    \"insurancePolicyNumber\": \"thyuj\",\r\n" + "    \"planNetworkIdentificationNumber\": \"zxc\",\r\n"
			+ "    \"agencyClaimNumber\": \"iuiui\",\r\n" + "          \"address\": {\r\n"
			+ "               \"address1\": \"123 address1\",\r\n" + "               \"address2\": \"cd\",\r\n"
			+ "               \"city\": \"city1\",\r\n" + "               \"state\": \"wa\",\r\n"
			+ "               \"postalCode\": \"981010000\",\r\n" + "               \"countryCode\": \"USA\",\r\n"
			+ "               \"locationIdentifier\": \"trg\",\r\n"
			+ "               \"countrySubDivisionCode\": \"oki\"\r\n" + "          },\r\n"
			+ "          \"providerCode\": \"AD\",\r\n" + "          \"referenceIdentificationQualifier\": \"9K\",\r\n"
			+ "          \"providerIdentifier\": \"dvxvz\",\r\n" + "        \"dateOfBirth\": \"18800102\",\r\n"
			+ "        \"gender\": \"M\",\r\n" + "        \"birthSequenceNumber\": \"345232\",\r\n"
			+ "          \"healthCareCodeInformation\": [\r\n" + "               {\r\n"
			+ "                    \"diagnosisTypeCode\": \"BK\",\r\n"
			+ "                    \"diagnosisCode\": \"ygy\"\r\n" + "               }\r\n" + "          ],\r\n"
			+ "          \"idCardIssueDate\": \"20100101\",\r\n" + "          \"planIssueDate\": \"20100101\",\r\n"
			+ "          \"informationStatusCode\": \"A\",\r\n" + "          \"employmentStatusCode\": \"fvdfvdf\",\r\n"
			+ "          \"governmentServiceAffiliationCode\": \"svsxc\",\r\n"
			+ "          \"description\": \"plplpl\",\r\n" + "          \"militaryServiceRankCode\":\"acasc\",\r\n"
			+ "          \"dateTimeFormatQualifier\": \"svsvsd\",\r\n" + "          \"dateTimePeriod\":\"10\",\r\n"
			+ "          \"startDateTimePeriod\":\"sdvsdv\",\r\n" + "          \"endDateTimePeriod\": \"svsdvx\"\r\n"
			+ "  },\r\n" + "  \"provider\": {\r\n" + "    \"organizationName\": \"happy123doctorsgroup\",\r\n"
			+ "    \"firstName\": \"rdcdet\",\r\n" + "    \"npi\": \"0123456a789\",\r\n"
			+ "    \"serviceProviderNumber\": \"654435\",\r\n" + "    \"payorID\": \"trdcrdr\",\r\n"
			+ "    \"taxId\": \"sdsvxc\",\r\n" + "    \"ssn\": \"23252422\",\r\n"
			+ "    \"pharmacyProcessorNumber\":\"dfbdcbdge\",\r\n" + "    \"servicesPlanID\": \"iuinuih\",\r\n"
			+ "    \"employersId\": \"75766\",\r\n" + "    \"providerCode\": \"AD\",\r\n"
			+ "    \"referenceIdentification\": \"ytftrg\",\r\n" + "    \"providerType\": \"payer\",\r\n"
			+ "    \"address\": {\r\n" + "        \"address1\": \"sdvxcvxcv\",\r\n"
			+ "        \"address2\": \"qqqq\",\r\n" + "        \"city\" : \"www\",\r\n"
			+ "        \"state\": \"eeeee\",\r\n" + "        \"postalCode\": \"65456\"\r\n" + "    }\r\n" + "  },\r\n"
			+ "     \"informationReceiverName\": {\r\n" + "          \"address\": {\r\n"
			+ "               \"address1\": \"123 address1\",\r\n" + "               \"address2\": \"qwert\",\r\n"
			+ "               \"city\": \"city1\",\r\n" + "               \"state\": \"wa\",\r\n"
			+ "               \"postalCode\": \"981010000\",\r\n" + "               \"countryCode\": \"6\",\r\n"
			+ "               \"locationIdentifier\": \"fv\",\r\n"
			+ "               \"countrySubDivisionCode\": \"ok\"\r\n" + "          },\r\n"
			+ "          \"submitterIdNumber\": \"cdetr\",\r\n"
			+ "          \"nationalProviderIdentifier\": \"eewaze\",\r\n"
			+ "          \"providerPlanNetworkIdNumber\": \"iniui\",\r\n"
			+ "          \"facilityNetworkIdNumber\": \"qzawaqw\",\r\n"
			+ "          \"priorIdentifierNumber\": \"oimijij\",\r\n"
			+ "          \"socialSecurityNumber\": \"uyyiyi\",\r\n"
			+ "          \"federalTaxpayerIdentificationNumber\": \"zxcv\",\r\n"
			+ "          \"informationReceiverAdditionalIdentifierState\": \"xcv\"\r\n" + "     },\r\n"
			+ "  \"dependents\": [\r\n" + "    {\r\n" + "        \"individualRelationshipCode\":\"01\",\r\n"
			+ "        \"birthSequenceNumber\": \"2311\",\r\n" + "        \"issueNumber\":\"svxvxc\",\r\n"
			+ "        \"eligibilityCategory\":\"cd\",\r\n" + "      \"firstName\": \"janeOne\",\r\n"
			+ "      \"lastName\": \"doeOne\",\r\n" + "      \"middleName\": \"middleone\",\r\n"
			+ "      \"suffix\":\"Mr\",\r\n" + "      \"dateOfBirth\": \"18160421\",\r\n"
			+ "      \"gender\": \"F\",\r\n" + "      \"ssn\": \"000000000\",\r\n"
			+ "      \"groupNumber\":\"1111111111\",\r\n" + "      \"idCard\":\"card123\",\r\n"
			+ "      \"providerCode\":\"AD\",\r\n" + "      \"referenceIdentificationQualifier\":\"9K\",\r\n"
			+ "      \"providerIdentifier\":\"dvxvz\",\r\n" + "      \"beginningCardIssueDate\": \"20101009\",\r\n"
			+ "      \"endCardIssueDate\": \"20101010\",\r\n" + "      \"memberId\": \"0000000000\",\r\n"
			+ "      \"beginningPlanIssueDate\": \"20101009\",\r\n" + "      \"endPlanIssueDate\": \"20101009\",\r\n"
			+ "               \"healthCareCodeInformation\": [\r\n" + "                    {\r\n"
			+ "                         \"diagnosisTypeCode\": \"BK\",\r\n"
			+ "                         \"diagnosisCode\": \"JIJI\"\r\n" + "                    }\r\n"
			+ "               ],\r\n" + "               \"address\": {\r\n"
			+ "                    \"address1\": \"123 address1\",\r\n"
			+ "                    \"address2\": \"SDCSDCX\",\r\n" + "                    \"city\": \"city1\",\r\n"
			+ "                    \"state\": \"wa\",\r\n" + "                    \"postalCode\": \"981010000\",\r\n"
			+ "                    \"countryCode\": \"usa\",\r\n"
			+ "                    \"locationIdentifier\": \"23123\",\r\n"
			+ "                    \"countrySubDivisionCode\": \"vdfvd\"\r\n" + "               },\r\n"
			+ "                \"additionalIdentification\": {\r\n"
			+ "                    \"identificationCardSerialNumber\": \"87878\",\r\n"
			+ "                    \"insurancePolicyNumber\": \"98989\",\r\n"
			+ "                    \"planNetworkIdentificationNumber\": \"8787\",\r\n"
			+ "                    \"agencyClaimNumber\": \"9876\"\r\n" + "               }\r\n" + "          \r\n"
			+ "	}\r\n" + "	],\r\n" + "     \"encounter\": {\r\n" + "          \"serviceTypeCodes\": [\r\n"
			+ "               \"10\",\r\n" + "               \"13\"\r\n" + "          ],\r\n"
			+ "          \"dateOfService\": \"20100101\",\r\n" + "          \"productOrServiceIDQualifier\":\"AD\",\r\n"
			+ "          \"procedureCode\":\"sw\"\r\n" + "     }\r\n" + "}";
	public static final String PROFESSIONALCLAIMS_HEALTHCHECK_URL = "https://sandbox.apigw.changehealthcare.com/medicalnetwork/professionalclaims/v3/healthcheck";
	public static final String PROFESSIONALCLAIMS_SUBMISSION_URL = "https://sandbox.apigw.changehealthcare.com/medicalnetwork/professionalclaims/v3/submission";
	public static final String PROFESSIONAL_SUBMISSION_JSON_STRING = "{\r\n"
			+ "  \"controlNumber\": \"000000001\",\r\n"
			+ "  \"tradingPartnerServiceId\": \"9496\",\r\n"
			+ "  \"submitter\": {\r\n"
			+ "    \"organizationName\": \"REGIONAL PPO NETWORK\",\r\n"
			+ "    \"contactInformation\": {\r\n"
			+ "      \"name\": \"SUBMITTER CONTACT INFO\",\r\n"
			+ "      \"phoneNumber\": \"123456789\"\r\n"
			+ "    }\r\n"
			+ "  },\r\n"
			+ "  \"receiver\": {\r\n"
			+ "    \"organizationName\": \"EXTRA HEALTHY INSURANCE\"\r\n"
			+ "  },\r\n"
			+ "  \"providers\": [{\r\n"
			+ "    \"providerType\": \"BillingProvider\",\r\n"
			+ "    \"npi\": \"1760854442\",\r\n"
			+ "    \"employerId\": \"123456789\",\r\n"
			+ "    \"organizationName\": \"HAPPY DOCTORS GROUPPRACTICE\",\r\n"
			+ "    \"address\": {\r\n"
			+ "      \"address1\": \"000 address1\",\r\n"
			+ "      \"city\": \"city2\",\r\n"
			+ "      \"state\": \"tn\",\r\n"
			+ "      \"postalCode\": \"372030000\"\r\n"
			+ "    },\r\n"
			+ "    \"contactInformation\": {\r\n"
			+ "      \"name\": \"janetwo doetwo\",\r\n"
			+ "      \"phoneNumber\": \"0000000001\"\r\n"
			+ "    }\r\n"
			+ "  },{\r\n"
			+ "    \"providerType\": \"ReferringProvider\",\r\n"
			+ "    \"npi\": \"1942788757\",\r\n"
			+ "    \"firstName\": \"johntwo\",\r\n"
			+ "    \"lastName\": \"doetwo\",\r\n"
			+ "    \"employerId\" : \"123456\",\r\n"
			+ "    \"address\": {\r\n"
			+ "      \"address1\": \"000 address1\",\r\n"
			+ "      \"city\": \"city2\",\r\n"
			+ "      \"state\": \"tn\",\r\n"
			+ "      \"postalCode\": \"372030000\"\r\n"
			+ "    },\r\n"
			+ "    \"contactInformation\": {\r\n"
			+ "      \"name\": \"janetwo doetwo\",\r\n"
			+ "      \"phoneNumber\": \"0000000001\"\r\n"
			+ "    }\r\n"
			+ "  },{\r\n"
			+ "    \"providerType\": \"RenderingProvider\",\r\n"
			+ "    \"npi\": \"1942788757\",\r\n"
			+ "    \"firstName\": \"janetwo\",\r\n"
			+ "    \"lastName\": \"doetwo\",\r\n"
			+ "    \"middleName\": \"middletwo\",\r\n"
			+ "    \"ssn\" : \"555443333\",\r\n"
			+ "    \"employerId\" : \"123456\",\r\n"
			+ "    \"address\": {\r\n"
			+ "      \"address1\": \"000 address1\",\r\n"
			+ "      \"city\": \"city2\",\r\n"
			+ "      \"state\": \"tn\",\r\n"
			+ "      \"postalCode\": \"372030000\"\r\n"
			+ "    },\r\n"
			+ "    \"contactInformation\": {\r\n"
			+ "      \"name\": \"janetwo doetwo\",\r\n"
			+ "      \"phoneNumber\": \"0000000001\"\r\n"
			+ "    }\r\n"
			+ "  }],\r\n"
			+ "   \"subscriber\": {\r\n"
			+ "        \"memberId\": \"0000000000\",\r\n"
			+ "		\"paymentResponsibilityLevelCode\": \"P\",\r\n"
			+ "        \"firstName\": \"johnOne\",\r\n"
			+ "        \"lastName\": \"doeOne\",\r\n"
			+ "        \"gender\": \"M\",\r\n"
			+ "        \"dateOfBirth\": \"18800102\",\r\n"
			+ "        \"ssn\": \"555443333\",\r\n"
			+ "        \"idCard\": \"card123\",\r\n"
			+ "		\"address\": {\r\n"
			+ "			\"address1\": \"000 address1\",\r\n"
			+ "			\"city\": \"city2\",\r\n"
			+ "			\"state\": \"tn\",\r\n"
			+ "			\"postalCode\": \"372030000\"\r\n"
			+ "		}\r\n"
			+ "    },\r\n"
			+ "  \"claimInformation\": {\r\n"
			+ "    \"claimFilingCode\": \"CI\",\r\n"
			+ "    \"patientControlNumber\": \"12345\",\r\n"
			+ "    \"claimChargeAmount\": \"28.75\",\r\n"
			+ "    \"placeOfServiceCode\": \"11\",\r\n"
			+ "    \"claimFrequencyCode\": \"1\",\r\n"
			+ "    \"signatureIndicator\": \"Y\",\r\n"
			+ "    \"planParticipationCode\": \"A\",\r\n"
			+ "    \"benefitsAssignmentCertificationIndicator\": \"Y\",\r\n"
			+ "    \"releaseInformationCode\": \"Y\",\r\n"
			+ "    \"claimSupplementalInformation\": {\r\n"
			+ "      \"repricedClaimNumber\": \"00001\",\r\n"
			+ "      \"claimNumber\": \"12345\"\r\n"
			+ "    },\r\n"
			+ "    \"healthCareCodeInformation\": [{\r\n"
			+ "      \"diagnosisTypeCode\": \"BK\",\r\n"
			+ "      \"diagnosisCode\": \"496\"\r\n"
			+ "    },{\r\n"
			+ "      \"diagnosisTypeCode\": \"BF\",\r\n"
			+ "      \"diagnosisCode\": \"25000\"\r\n"
			+ "    }],\r\n"
			+ "    \"serviceFacilityLocation\": {\r\n"
			+ "      \"organizationName\": \"HAPPY DOCTORS GROUP\",\r\n"
			+ "      \"address\": {\r\n"
			+ "        \"address1\": \"000 address1\",\r\n"
			+ "        \"city\": \"city2\",\r\n"
			+ "        \"state\": \"tn\",\r\n"
			+ "        \"postalCode\": \"372030000\"\r\n"
			+ "      }\r\n"
			+ "      },\r\n"
			+ "    \"serviceLines\":[ {\r\n"
			+ "      \"serviceDate\": \"20050514\",\r\n"
			+ "      \"professionalService\": {\r\n"
			+ "        \"procedureIdentifier\": \"HC\",\r\n"
			+ "        \"lineItemChargeAmount\": \"25\",\r\n"
			+ "        \"procedureCode\": \"E0570\",\r\n"
			+ "        \"measurementUnit\": \"UN\",\r\n"
			+ "        \"serviceUnitCount\": \"1\",\r\n"
			+ "        \"compositeDiagnosisCodePointers\": {\r\n"
			+ "          \"diagnosisCodePointers\": [\"1\",\"2\"]\r\n"
			+ "        }\r\n"
			+ "      }\r\n"
			+ "      },\r\n"
			+ "      {\r\n"
			+ "        \"serviceDate\": \"20050514\",\r\n"
			+ "        \"professionalService\": {\r\n"
			+ "          \"procedureIdentifier\": \"HC\",\r\n"
			+ "          \"lineItemChargeAmount\": \"3.75\",\r\n"
			+ "          \"procedureCode\": \"A7003\",\r\n"
			+ "          \"measurementUnit\": \"UN\",\r\n"
			+ "          \"serviceUnitCount\": \"1\",\r\n"
			+ "          \"compositeDiagnosisCodePointers\": {\r\n"
			+ "            \"diagnosisCodePointers\": [\"1\" ]\r\n"
			+ "          }\r\n"
			+ "        }\r\n"
			+ "        }\r\n"
			+ "    ]\r\n"
			+ "\r\n"
			+ "  }\r\n"
			+ "}";

	public static final String PROFESSIONALCLAIMS_VALIDATION_URL = "https://sandbox.apigw.changehealthcare.com/medicalnetwork/professionalclaims/v3/validation";
	public static final String PROFESSIONAL_VALIDATION_JSON_STRING = "{\r\n"
			+ "			  \"controlNumber\": \"000000001\",\r\n"
			+ "			  \"tradingPartnerServiceId\": \"9496\",\r\n"
			+ "			  \"submitter\": {\r\n"
			+ "					  \"contactInformation\": {\r\n"
			+ "						   \"name\": \"SUBMITTER CONTACT INFO\",\r\n"
			+ "						   \"phoneNumber\": \"0000000000\",\r\n"
			+ "						   \"faxNumber\": \"0000000000\",\r\n"
			+ "						   \"phoneExtension\": \"1234\",\r\n"
			+ "						   \"email\": \"email@email.com\"\r\n"
			+ "					  },\r\n"
			+ "					  \"organizationName\": \"REGIONAL PPO NETWORK\",\r\n"
			+ "					  \"middleName\": \"middleone\"\r\n"
			+ "				 },\r\n"
			+ "			  \"receiver\": {\r\n"
			+ "			    \"organizationName\": \"EXTRA HEALTHY INSURANCE\"\r\n"
			+ "			  },\r\n"
			+ "			  \"subscriber\": {\r\n"
			+ "			    \"memberId\": \"0000000001\",\r\n"
			+ "			    \"paymentResponsibilityLevelCode\": \"P\",\r\n"
			+ "			    \"firstName\": \"johnone\",\r\n"
			+ "			    \"lastName\": \"doeOne\",\r\n"
			+ "			    \"gender\": \"M\",\r\n"
			+ "			    \"dateOfBirth\": \"19800102\",\r\n"
			+ "			    \"policyNumber\": \"00001\",\r\n"
			+ "				\"insuranceTypeCode\": \"12\",\r\n"
			+ "				\"subscriberGroupName\": \"Subscriber Group Name\",\r\n"
			+ "				\"middleName\": \"middleone\",\r\n"
			+ "				\"groupNumber\": \"0000000000\",\r\n"
			+ "				\"ssn\": \"000000000\",\r\n"
			+ "				  \"address\": {\r\n"
			+ "					   \"address1\": \"123 address1\",\r\n"
			+ "					   \"address2\": \"apt 000\",\r\n"
			+ "					   \"city\": \"city1\",\r\n"
			+ "					   \"state\": \"wa\",\r\n"
			+ "					   \"postalCode\": \"981010000\",\r\n"
			+ "					   \"countryCode\": \"cd\",\r\n"
			+ "					   \"countrySubDivisionCode\": \"cd\"\r\n"
			+ "				  },\r\n"
			+ "				  \"contactInformation\": {\r\n"
			+ "					   \"name\": \"SUBMITTER CONTACT INFO\",\r\n"
			+ "					   \"phoneNumber\": \"0000000000\",\r\n"
			+ "					   \"faxNumber\": \"0000000000\",\r\n"
			+ "					   \"email\": \"email@email.com\",\r\n"
			+ "					   \"phoneExtension\": \"1234\"\r\n"
			+ "				  }\r\n"
			+ "			  },\r\n"
			+ "			  \"dependent\": {\r\n"
			+ "			    \"memberId\": \"0000000002\",\r\n"
			+ "			    \"paymentResponsibilityLevelCode\": \"P\",\r\n"
			+ "			    \"firstName\": \"janeone\",\r\n"
			+ "			    \"lastName\": \"doeOne\",\r\n"
			+ "				\"middleName\": \"middleone\",\r\n"
			+ "			    \"gender\": \"F\",\r\n"
			+ "			    \"dateOfBirth\": \"19800102\",\r\n"
			+ "			    \"policyNumber\": \"00002\",\r\n"
			+ "			    \"relationshipToSubscriberCode\": \"01\",\r\n"
			+ "				  \"contactInformation\": {\r\n"
			+ "					   \"name\": \"SUBMITTER CONTACT INFO\",\r\n"
			+ "					   \"phoneNumber\": \"0000000000\",\r\n"
			+ "					   \"faxNumber\": \"0000000000\",\r\n"
			+ "					   \"email\": \"email@email.com\",\r\n"
			+ "					   \"phoneExtension\": \"1234\"\r\n"
			+ "				  },\r\n"
			+ "			    \"address\": {\r\n"
			+ "					   \"address1\": \"123 address1\",\r\n"
			+ "					   \"address2\": \"apt 000\",\r\n"
			+ "					   \"city\": \"city1\",\r\n"
			+ "					   \"state\": \"wa\",\r\n"
			+ "					   \"postalCode\": \"981010000\"\r\n"
			+ "					}\r\n"
			+ "			  },\r\n"
			+ "				 \"payToAddress\": {\r\n"
			+ "					  \"address2\": \"apt 000\",\r\n"
			+ "					  \"address1\": \"123 address1\",\r\n"
			+ "					  \"city\": \"city1\",\r\n"
			+ "					  \"state\": \"wa\",\r\n"
			+ "					  \"postalCode\": \"981010000\"\r\n"
			+ "				 },\r\n"
			+ "				 \"payToPlan\": {\r\n"
			+ "					  \"address\": {\r\n"
			+ "						   \"address1\": \"123 address1\",\r\n"
			+ "						   \"address2\": \"apt 000\",\r\n"
			+ "						   \"city\": \"city1\",\r\n"
			+ "						   \"state\": \"wa\",\r\n"
			+ "						   \"postalCode\": \"981010000\"\r\n"
			+ "					  },\r\n"
			+ "					  \"organizationName\": \"Example Org\",\r\n"
			+ "					  \"primaryIdentifierTypeCode\": \"XV\",\r\n"
			+ "					  \"primaryIdentifier\": \"gtgt\",\r\n"
			+ "					  \"secondaryIdentifier\": \"11\",\r\n"
			+ "					  \"secondaryIdentifierTypeCode\": \"2U\",\r\n"
			+ "					  \"taxIdentificationNumber\": \"DF\"\r\n"
			+ "				 },\r\n"
			+ "					 \"payerAddress\": {\r\n"
			+ "						  \"address2\": \"apt 000\",\r\n"
			+ "						  \"address1\": \"123 address1\",\r\n"
			+ "						  \"city\": \"city1\",\r\n"
			+ "						  \"state\": \"wa\",\r\n"
			+ "						  \"postalCode\": \"981010000\"\r\n"
			+ "					 },\r\n"
			+ "					 \"billing\": {\r\n"
			+ "						  \"address\": {\r\n"
			+ "							   \"address1\": \"123 address1\",\r\n"
			+ "							   \"address2\": \"apt 000\",\r\n"
			+ "							   \"city\": \"city1\",\r\n"
			+ "							   \"state\": \"wa\",\r\n"
			+ "							   \"postalCode\": \"981010000\"\r\n"
			+ "						  },\r\n"
			+ "						  \"contactInformation\": {\r\n"
			+ "							   \"name\": \"SUBMITTER CONTACT INFO\",\r\n"
			+ "							   \"phoneNumber\": \"0000000000\",\r\n"
			+ "							   \"faxNumber\": \"0000000000\",\r\n"
			+ "							   \"email\": \"email@email.com\",\r\n"
			+ "							   \"phoneExtension\": \"1234\"\r\n"
			+ "						  },\r\n"
			+ "						  \"providerType\": \"BillingProvider\",\r\n"
			+ "						  \"npi\": \"1760854442\",\r\n"
			+ "						  \"ssn\": \"000000000\",\r\n"
			+ "						  \"employerId\": \"123456789\",\r\n"
			+ "						  \"commercialNumber\": \"sdvsdv\",\r\n"
			+ "						  \"locationNumber\": \"sdvsdv\",\r\n"
			+ "						  \"payerIdentificationNumber\": \"sdvsdv\",\r\n"
			+ "						  \"employerIdentificationNumber\": \"sdvsdv\",\r\n"
			+ "						  \"claimOfficeNumber\": \"sdvsdv\",\r\n"
			+ "						  \"stateLicenseNumber\": \"0000000\",\r\n"
			+ "						  \"providerUpinNumber\": \"dfvdfv\",\r\n"
			+ "						  \"taxonomyCode\": \"DF\",\r\n"
			+ "						  \"firstName\": \"johnone\",\r\n"
			+ "						  \"lastName\": \"doeone\",\r\n"
			+ "						  \"middleName\": \"middleone\",\r\n"
			+ "						  \"organizationName\": \"HAPPY DOCTORS GROUPPRACTICE\"\r\n"
			+ "					 },\r\n"
			+ "			  \"providers\": [{\r\n"
			+ "			    \"providerType\": \"BillingProvider\",\r\n"
			+ "			    \"npi\": \"1760854442\",\r\n"
			+ "			    \"employerId\": \"123456789\",\r\n"
			+ "			    \"organizationName\": \"HAPPY DOCTORS GROUPPRACTICE\",\r\n"
			+ "               \"locationNumber\": \"jm\",\r\n"
			+ "               \"payerIdentificationNumber\": \"jm\",\r\n"
			+ "               \"commercialNumber\": \"jm\",\r\n"
			+ "               \"employerIdentificationNumber\": \"jm\",\r\n"
			+ "               \"claimOfficeNumber\": \"mj\",\r\n"
			+ "               \"stateLicenseNumber\": \"0000000\",\r\n"
			+ "               \"providerUpinNumber\": \"mj\",\r\n"
			+ "               \"taxonomyCode\": \"mj\",\r\n"
			+ "               \"middleName\": \"middleone\",\r\n"
			+ "              \"firstName\":\"johnone\",\r\n"
			+ "              \"lastName\":\"doeone\",\r\n"
			+ "               \"ssn\": \"000000000\",\r\n"
			+ "			    \"address\": {\r\n"
			+ "			      \"address1\": \"000 address1\",\r\n"
			+ "			      \"city\": \"city2\",\r\n"
			+ "			      \"state\": \"tn\",\r\n"
			+ "			      \"postalCode\": \"372030000\"\r\n"
			+ "			    },\r\n"
			+ "			    \"contactInformation\": {\r\n"
			+ "			      \"name\": \"janetwo doetwo\",\r\n"
			+ "			      \"phoneNumber\": \"0000000001\"\r\n"
			+ "			    }\r\n"
			+ "			  }],\r\n"
			+ "	\"claimInformation\": {\r\n"
			+ "          \"otherSubscriberInformation\": [\r\n"
			+ "               {\r\n"
			+ "                    \"otherSubscriberName\": {\r\n"
			+ "                         \"otherInsuredQualifier\": \"1\",\r\n"
			+ "                         \"otherInsuredLastName\": \"Doe\",\r\n"
			+ "                         \"otherInsuredFirstName\": \"John\",\r\n"
			+ "                         \"otherInsuredMiddleName\": \"middle\",\r\n"
			+ "                         \"otherInsuredNameSuffix\": \"Dr\",\r\n"
			+ "                         \"otherInsuredIdentifierTypeCode\": \"II\",\r\n"
			+ "                         \"otherInsuredIdentifier\": \"Missing\"\r\n"
			+ "                    },\r\n"
			+ "                    \"otherPayerName\": { \r\n"
			+ "						 \"otherPayerSecondaryIdentifier\": [\r\n"
			+ "                              {\r\n"
			+ "                                   \"qualifier\": \"EI\",\r\n"
			+ "                                   \"identifier\": \"191919199\",\r\n"
			+ "                                   \"otherIdentifier\": \"oident\"\r\n"
			+ "                              }\r\n"
			+ "                         ],\r\n"
			+ "                         \"otherInsuredAdditionalIdentifier\": \"InsuredIdentifier\",\r\n"
			+ "                         \"otherPayerOrganizationName\": \"Doe\",\r\n"
			+ "                         \"otherPayerIdentifierTypeCode\": \"PI\",\r\n"
			+ "                         \"otherPayerIdentifier\": \"PayerIdentifier\",\r\n"
			+ "                         \"otherPayerPriorAuthorizationNumber\": \"121\",\r\n"
			+ "                         \"otherPayerPriorAuthorizationOrReferralNumber\": \"212\",\r\n"
			+ "                         \"otherPayerClaimAdjustmentIndicator\": true,\r\n"
			+ "                         \"otherPayerClaimControlNumber\": \"123456789\"\r\n"
			+ "                    },\r\n"
			+ "                    \"otherPayerReferringProvider\": [\r\n"
			+ "                         {\r\n"
			+ "                              \"otherPayerReferringProviderIdentifier\": [\r\n"
			+ "                                   {\r\n"
			+ "                                        \"qualifier\": \"0B\",\r\n"
			+ "                                        \"identifier\": \"0B\",\r\n"
			+ "                                        \"otherIdentifier\": \"OIDEN\"\r\n"
			+ "                                   }\r\n"
			+ "                              ]\r\n"
			+ "						 }\r\n"
			+ "					],\r\n"
			+ "                    \"paymentResponsibilityLevelCode\": \"S\",\r\n"
			+ "                    \"individualRelationshipCode\": \"01\",\r\n"
			+ "                    \"claimFilingIndicatorCode\": \"ZZ\",\r\n"
			+ "                    \"benefitsAssignmentCertificationIndicator\": \"Y\",\r\n"
			+ "                    \"releaseOfInformationCode\": \"Y\",\r\n"
			+ "                    \"nonCoveredChargeAmount\": \"28.75\",\r\n"
			+ "                    \"remainingPatientLiability\": \"71.25\"\r\n"
			+ "               }\r\n"
			+ "          ],\r\n"
			+ "			  \"claimSupplementalInformation\": {\r\n"
			+ "				   \"reportInformation\": {\r\n"
			+ "						\"attachmentReportTypeCode\": \"B2\",\r\n"
			+ "						\"attachmentTransmissionCode\": \"BM\",\r\n"
			+ "						\"attachmentControlNumber\": \"dfvdfv\"\r\n"
			+ "				   },\r\n"
			+ "				   \"priorAuthorizationNumber\": \"00000\",\r\n"
			+ "				   \"claimNumber\":\"00000\",\r\n"
			+ "				   \"referralNumber\":\"00000\",\r\n"
			+ "				   \"claimControlNumber\":\"00000\",\r\n"
			+ "				   \"repricedClaimNumber\":\"00000\",\r\n"
			+ "				   \"adjustedRepricedClaimNumber\":\"00000\",\r\n"
			+ "				   \"investigationalDeviceExemptionNumber\":\"00000\",\r\n"
			+ "				   \"mammographyCertificationNumber\":\"00000\",\r\n"
			+ "				   \"medicalRecordNumber\":\"00000\",\r\n"
			+ "				   \"demoProjectIdentifier\":\"00000\",\r\n"
			+ "				   \"carePlanOversightNumber\":\"00000\",\r\n"
			+ "				   \"medicareCrossoverReferenceId\":\"00000\",\r\n"
			+ "				   \"serviceAuthorizationExceptionCode\":\"1\"\r\n"
			+ "			  },\r\n"
			+ "			  \"ambulanceCertification\": [\r\n"
			+ "				   {\r\n"
			+ "						\"conditionCodes\": [\r\n"
			+ "							 \"01\",\r\n"
			+ "							 \"05\"\r\n"
			+ "						],\r\n"
			+ "						\"certificationConditionIndicator\": \"Y\",\r\n"
			+ "						\"sequenceOrder\":\"21\",\r\n"
			+ "						\"conditionCode\":\"12\"\r\n"
			+ "				   },\r\n"
			+ "				   {\r\n"
			+ "						\"conditionCodes\": [\r\n"
			+ "							 \"09\",\r\n"
			+ "							 \"08\"\r\n"
			+ "						],\r\n"
			+ "						\"certificationConditionIndicator\": \"Y\",\r\n"
			+ "						\"sequenceOrder\":\"21\",\r\n"
			+ "						\"conditionCode\":\"12\"\r\n"
			+ "				   }\r\n"
			+ "			  ],\r\n"
			+ "			  \"healthCareCodeInformation\": [\r\n"
			+ "				   {\r\n"
			+ "						\"diagnosisTypeCode\": \"BK\",\r\n"
			+ "						\"diagnosisCode\": \"cd\"\r\n"
			+ "				   },\r\n"
			+ "				   {\r\n"
			+ "						\"diagnosisTypeCode\": \"BF\",\r\n"
			+ "						\"diagnosisCode\": \"cd\"\r\n"
			+ "				   }\r\n"
			+ "			  ],\r\n"
			+ "			  \"anesthesiaRelatedSurgicalProcedure\": [\r\n"
			+ "				   \"vsdvsdv\",\r\n"
			+ "				   \"sdvsdcbcvb\"\r\n"
			+ "			  ],\r\n"
			+ "			  \"epsdtReferral\": {\r\n"
			+ "				   \"conditionCodes\": [\r\n"
			+ "						\"NU\"\r\n"
			+ "				   ],\r\n"
			+ "				   \"certificationConditionCodeAppliesIndicator\": \"N\"\r\n"
			+ "			  },\r\n"
			+ "			  \"conditionInformation\": [\r\n"
			+ "				   {\r\n"
			+ "						\"conditionCodes\": [\r\n"
			+ "							 \"sd\",\r\n"
			+ "							 \"ds\"\r\n"
			+ "						],\r\n"
			+ "						\"sequenceOrder\":\"21\",\r\n"
			+ "						\"conditionCode\":\"12\"\r\n"
			+ "				   },\r\n"
			+ "				   {\r\n"
			+ "						\"conditionCodes\": [\r\n"
			+ "							 \"gs\",\r\n"
			+ "							 \"gt\"\r\n"
			+ "						],\r\n"
			+ "						\"sequenceOrder\":\"21\",\r\n"
			+ "						\"conditionCode\":\"12\"\r\n"
			+ "				   }\r\n"
			+ "			  ],\r\n"
			+ "			  \"ambulanceTransportInformation\": {\r\n"
			+ "				   \"patientWeightInPounds\": \"154\",\r\n"
			+ "				   \"ambulanceTransportReasonCode\": \"A\",\r\n"
			+ "				   \"transportDistanceInMiles\": \"10\",\r\n"
			+ "				   \"roundTripPurposeDescription\": \"we\",\r\n"
			+ "				   \"stretcherPurposeDescription\": \"ew\"\r\n"
			+ "			  },\r\n"
			+ "			  \"claimNote\": {\r\n"
			+ "				   \"additionalInformation\": \"re\"\r\n"
			+ "			  },\r\n"
			+ "			  \"spinalManipulationServiceInformation\": {\r\n"
			+ "				   \"patientConditionCode\": \"A\",\r\n"
			+ "				   \"patientConditionDescription1\": \"A\",\r\n"
			+ "				   \"patientConditionDescription2\": \"cs\"\r\n"
			+ "			  },\r\n"
			+ "			  \"patientConditionInformationVision\": [\r\n"
			+ "				   {\r\n"
			+ "						\"conditionCodes\": [\r\n"
			+ "							 \"L1\",\r\n"
			+ "							 \"L2\"\r\n"
			+ "						],\r\n"
			+ "						\"codeCategory\": \"E1\",\r\n"
			+ "						\"certificationConditionIndicator\": \"N\",\r\n"
			+ "						\"sequenceOrder\":\"21\"\r\n"
			+ "				   },\r\n"
			+ "				   {\r\n"
			+ "						\"conditionCodes\": [\r\n"
			+ "							 \"L3\",\r\n"
			+ "							 \"L5\"\r\n"
			+ "						],\r\n"
			+ "						\"codeCategory\": \"E1\",\r\n"
			+ "						\"certificationConditionIndicator\": \"N\",\r\n"
			+ "						\"sequenceOrder\":\"21\"\r\n"
			+ "				   }\r\n"
			+ "			  ],\r\n"
			+ "			  \"serviceFacilityLocation\": {\r\n"
			+ "				   \"address\": {\r\n"
			+ "						\"address1\": \"123 address1\",\r\n"
			+ "						\"address2\": \"apt 000\",\r\n"
			+ "						\"city\": \"city1\",\r\n"
			+ "						\"state\": \"wa\",\r\n"
			+ "						\"postalCode\": \"981010000\"\r\n"
			+ "				   },\r\n"
			+ "				   \"secondaryIdentifier\": [\r\n"
			+ "						{\r\n"
			+ "							 \"qualifier\": \"G2\",\r\n"
			+ "							 \"identifier\": \"21\"\r\n"
			+ "						},\r\n"
			+ "						{\r\n"
			+ "							 \"qualifier\": \"0B\",\r\n"
			+ "							 \"identifier\": \"34\"\r\n"
			+ "						}\r\n"
			+ "				   ],\r\n"
			+ "				   \"organizationName\": \"HAPPY DOCTORS GROUP\",\r\n"
			+ "				   \"npi\": \"34234234\",\r\n"
			+ "				   \"phoneName\": \"1212234\",\r\n"
			+ "				   \"phoneNumber\": \"234234234\",\r\n"
			+ "				   \"phoneExtension\": \"235234534\",\r\n"
			+ "				   \"IdentificationQualifierCode\":\"0B\"\r\n"
			+ "			  },\r\n"
			+ "			  \"claimContractInformation\": {\r\n"
			+ "				   \"contractTypeCode\": \"01\",\r\n"
			+ "				   \"contractAmount\": \"12\",\r\n"
			+ "				   \"contractPercentage\": \"1\",\r\n"
			+ "				   \"contractCode\": \"1\",\r\n"
			+ "				   \"termsDiscountPercentage\": \"1\",\r\n"
			+ "				   \"contractVersionIdentifier\": \"111111\"\r\n"
			+ "			  },\r\n"
			+ "			  \"fileInformationList\": [\r\n"
			+ "				   \"12\",\r\n"
			+ "				   \"13\"\r\n"
			+ "			  ],\r\n"
			+ "			  \"ambulancePickUpLocation\": {\r\n"
			+ "				   \"address1\": \"123 address1\",\r\n"
			+ "				   \"address2\": \"apt 000\",\r\n"
			+ "				   \"city\": \"city1\",\r\n"
			+ "				   \"state\": \"wa\",\r\n"
			+ "				   \"postalCode\": \"981010000\"\r\n"
			+ "			  },\r\n"
			+ "			  \"ambulanceDropOffLocation\": {\r\n"
			+ "				   \"address1\": \"123 address1\",\r\n"
			+ "				   \"address2\": \"apt 000\",\r\n"
			+ "				   \"city\": \"city1\",\r\n"
			+ "				   \"state\": \"wa\",\r\n"
			+ "				   \"postalCode\": \"981010000\"\r\n"
			+ "			  },\r\n"
			+ "			  \"claimPricingRepricingInformation\": {\r\n"
			+ "				   \"pricingMethodologyCode\": \"01\",\r\n"
			+ "				   \"repricedAllowedAmount\": \"1\",\r\n"
			+ "				   \"repricedSavingAmount\": \"21\",\r\n"
			+ "				   \"repricingOrganizationIdentifier\": \"21\",\r\n"
			+ "				   \"repricingPerDiemOrFlatRateAmoung\": \"12\",\r\n"
			+ "				   \"repricedApprovedAmbulatoryPatientGroupCode\": \"12\",\r\n"
			+ "				   \"repricedApprovedAmbulatoryPatientGroupAmount\": \"21\",\r\n"
			+ "				   \"rejectReasonCode\": \"T1\",\r\n"
			+ "				   \"policyComplianceCode\": \"1\",\r\n"
			+ "				   \"exceptionCode\": \"2\"\r\n"
			+ "			  },\r\n"
			+ "			  \"claimFilingCode\": \"CI\",\r\n"
			+ "			  \"propertyCasualtyClaimNumber\": \"00000\",\r\n"
			+ "			  \"patientWeight\": \"56\",\r\n"
			+ "			  \"deathDate\": \"20100101\",\r\n"
			+ "			  \"pregnancyIndicator\": \"Y\",\r\n"
			+ "			  \"patientSignatureSourceCode\": true,\r\n"
			+ "			  \"specialProgramCode\": \"02\",\r\n"
			+ "			  \"delayReasonCode\": \"1\",\r\n"
			+ "			  \"homeboundIndicator\": true,\r\n"
			+ "			  \"patientAmountPaid\": \"100\",\r\n"
			+ "			  \"autoAccidentCountryCode\": \"USA\",\r\n"
			+ "			  \"autoAccidentStateCode\": \"AA\",\r\n"
			+ "			  \"claimDateInformation\": {\r\n"
			+ "			  \"symptomDate\": \"20100101\",\r\n"
			+ "			  \"lastMenstrualPeriodDate\": \"20100101\",\r\n"
			+ "			  \"lastXRayDate\": \"20100101\",\r\n"
			+ "			  \"initialTreatmentDate\": \"20100101\",\r\n"
			+ "			  \"lastSeenDate\": \"20100101\",\r\n"
			+ "			  \"admissionDate\": \"20100101\",\r\n"
			+ "			  \"dischargeDate\": \"20100101\",\r\n"
			+ "			  \"hearingAndVisionPrescriptionDate\": \"20100101\",\r\n"
			+ "			  \"assumedAndRelinquishedCareBeginDate\": \"20100101\",\r\n"
			+ "			  \"assumedAndRelinquishedCareEndDate\": \"20100101\",\r\n"
			+ "			  \"repricerReceivedDate\": \"20100101\",\r\n"
			+ "			  \"firstContactDate\": \"20100101\",\r\n"
			+ "			  \"lastWorkedDate\": \"20100101\",\r\n"
			+ "			  \"authorizedReturnToWorkDate\": \"20100101\",\r\n"
			+ "			  \"accidentDate\": \"20100101\"\r\n"
			+ "		  },\r\n"
			+ "          \"relatedCausesCode\": [\r\n"
			+ "               \"AA\",\r\n"
			+ "               \"EM\"\r\n"
			+ "          ],\r\n"
			+ "			    \"patientControlNumber\": \"12345\",\r\n"
			+ "			    \"claimChargeAmount\": \"28.75\",\r\n"
			+ "			    \"placeOfServiceCode\": \"11\",\r\n"
			+ "			    \"claimFrequencyCode\": \"1\",\r\n"
			+ "			    \"signatureIndicator\": \"Y\",\r\n"
			+ "			    \"planParticipationCode\": \"A\",\r\n"
			+ "			    \"benefitsAssignmentCertificationIndicator\": \"Y\",\r\n"
			+ "			    \"releaseInformationCode\": \"Y\",\r\n"
			+ "			    \"claimSupplementalInformation\": {\r\n"
			+ "			      \"repricedClaimNumber\": \"00001\",\r\n"
			+ "			      \"claimNumber\": \"12345\"\r\n"
			+ "			    },\r\n"
			+ "			    \"healthCareCodeInformation\": [{\r\n"
			+ "			      \"diagnosisTypeCode\": \"ABK\",\r\n"
			+ "			      \"diagnosisCode\": \"S93401A\"\r\n"
			+ "			    },{\r\n"
			+ "			      \"diagnosisTypeCode\": \"ABF\",\r\n"
			+ "			      \"diagnosisCode\": \"S72044G\"\r\n"
			+ "			    }],\r\n"
			+ "			    \"serviceFacilityLocation\": {\r\n"
			+ "			      \"organizationName\": \"HAPPY DOCTORS GROUP\",\r\n"
			+ "			      \"address\": {\r\n"
			+ "			        \"address1\": \"000 address1\",\r\n"
			+ "			        \"city\": \"city2\",\r\n"
			+ "			        \"state\": \"tn\",\r\n"
			+ "			        \"postalCode\": \"372030000\"\r\n"
			+ "			      }\r\n"
			+ "			      },\r\n"
			+ "			    \"serviceLines\":[ {\r\n"
			+ "			      \"serviceDate\": \"20180514\",\r\n"
			+ "			      \"professionalService\": {\r\n"
			+ "			        \"procedureIdentifier\": \"HC\",\r\n"
			+ "			        \"lineItemChargeAmount\": \"25\",\r\n"
			+ "			        \"procedureCode\": \"E0570\",\r\n"
			+ "			        \"measurementUnit\": \"UN\",\r\n"
			+ "			        \"serviceUnitCount\": \"1\",\r\n"
			+ "			        \"compositeDiagnosisCodePointers\": {\r\n"
			+ "			          \"diagnosisCodePointers\": [\"1\",\"2\"]\r\n"
			+ "			        }\r\n"
			+ "			      }\r\n"
			+ "			      },\r\n"
			+ "			      {\r\n"
			+ "			        \"serviceDate\": \"20180514\",\r\n"
			+ "			        \"professionalService\": {\r\n"
			+ "			          \"procedureIdentifier\": \"HC\",\r\n"
			+ "			          \"lineItemChargeAmount\": \"3.75\",\r\n"
			+ "			          \"procedureCode\": \"A7003\",\r\n"
			+ "			          \"measurementUnit\": \"UN\",\r\n"
			+ "			          \"serviceUnitCount\": \"1\",\r\n"
			+ "			          \"compositeDiagnosisCodePointers\": {\r\n"
			+ "			            \"diagnosisCodePointers\": [\"1\" ]\r\n"
			+ "			          }\r\n"
			+ "			        }\r\n"
			+ "			        }\r\n"
			+ "			    ]\r\n"
			+ "			\r\n"
			+ "			  },\r\n"
			+ "          \"serviceLines\": [\r\n"
			+ "               {\r\n"
			+ "                    \"professionalService\": {\r\n"
			+ "                         \"procedureModifiers\": [\r\n"
			+ "                              \"20050514\",\r\n"
			+ "                              \"20050514\"\r\n"
			+ "                         ],\r\n"
			+ "                         \"compositeDiagnosisCodePointers\": {\r\n"
			+ "                              \"diagnosisCodePointers\": [\r\n"
			+ "                                   \"20050514\",\r\n"
			+ "                                   \"20050514\"\r\n"
			+ "                              ]\r\n"
			+ "                         },\r\n"
			+ "                         \"procedureIdentifier\": \"HC\",\r\n"
			+ "                         \"procedureCode\": \"E0570\",\r\n"
			+ "                         \"lineItemChargeAmount\": \"25\",\r\n"
			+ "                         \"measurementUnit\": \"UN\",\r\n"
			+ "                         \"serviceUnitCount\": \"1\",\r\n"
			+ "                         \"placeOfServiceCode\": \"20050514\"\r\n"
			+ "                    },\r\n"
			+ "                    \"durableMedicalEquipmentService\": {\r\n"
			+ "                         \"days\": \"20050514\",\r\n"
			+ "                         \"rentalPrice\": \"20050514\",\r\n"
			+ "                         \"purchasePrice\": \"20050514\",\r\n"
			+ "                         \"frequencyCode\": \"1\"\r\n"
			+ "                    },\r\n"
			+ "                    \"serviceLineSupplementalInformation\": [\r\n"
			+ "                         {\r\n"
			+ "                              \"attachmentReportTypeCode\": \"B2\",\r\n"
			+ "                              \"attachmentTransmissionCode\": \"BM\",\r\n"
			+ "                              \"attachmentControlNumber\": \"20050514\"\r\n"
			+ "                         },\r\n"
			+ "                         {\r\n"
			+ "                              \"attachmentReportTypeCode\": \"B2\",\r\n"
			+ "                              \"attachmentTransmissionCode\": \"BM\",\r\n"
			+ "                              \"attachmentControlNumber\": \"20050514\"\r\n"
			+ "                         }\r\n"
			+ "                    ],\r\n"
			+ "                    \"durableMedicalEquipmentCertificateOfMedicalNecessity\": {\r\n"
			+ "                         \"attachmentTransmissionCode\": \"AB\"\r\n"
			+ "                    },\r\n"
			+ "                    \"ambulanceTransportInformation\": {\r\n"
			+ "                         \"patientWeightInPounds\": \"20050514\",\r\n"
			+ "                         \"ambulanceTransportReasonCode\": \"A\",\r\n"
			+ "                         \"transportDistanceInMiles\": \"20050514\",\r\n"
			+ "                         \"roundTripPurposeDescription\": \"20050514\",\r\n"
			+ "                         \"stretcherPurposeDescription\": \"20050514\"\r\n"
			+ "                    },\r\n"
			+ "                    \"durableMedicalEquipmentCertification\": {\r\n"
			+ "                         \"certificationTypeCode\": \"I\",\r\n"
			+ "                         \"durableMedicalEquipmentDurationInMonths\": \"20050514\"\r\n"
			+ "                    },\r\n"
			+ "                    \"ambulanceCertification\": [\r\n"
			+ "                         {\r\n"
			+ "                              \"conditionCodes\": [\r\n"
			+ "                                   \"08\",\r\n"
			+ "                                   \"01\"\r\n"
			+ "                              ],\r\n"
			+ "                              \"certificationConditionIndicator\": \"Y\"\r\n"
			+ "                         },\r\n"
			+ "                         {\r\n"
			+ "                              \"conditionCodes\": [\r\n"
			+ "                                   \"07\",\r\n"
			+ "                                   \"01\"\r\n"
			+ "                              ],\r\n"
			+ "                              \"certificationConditionIndicator\": \"N\"\r\n"
			+ "                         }\r\n"
			+ "                    ],\r\n"
			+ "                    \"conditionIndicatorDurableMedicalEquipment\": {\r\n"
			+ "                         \"certificationConditionIndicator\": \"N\",\r\n"
			+ "                         \"conditionIndicator\": \"ZV\",\r\n"
			+ "                         \"conditionIndicatorCode\": \"ZV\"\r\n"
			+ "                    },\r\n"
			+ "                    \"serviceLineDateInformation\": {\r\n"
			+ "                         \"prescriptionDate\": \"20050514\",\r\n"
			+ "                         \"certificationRevisionOrRecertificationDate\": \"20050514\",\r\n"
			+ "                         \"beginTherapyDate\": \"20050514\",\r\n"
			+ "                         \"lastCertificationDate\": \"20050514\",\r\n"
			+ "                         \"treatmentOrTherapyDate\": \"20050514\",\r\n"
			+ "                         \"hemoglobinTestDate\": \"20050514\",\r\n"
			+ "                         \"serumCreatineTestDate\": \"20050514\",\r\n"
			+ "                         \"shippedDate\": \"20050514\",\r\n"
			+ "                         \"lastXRayDate\": \"20050514\",\r\n"
			+ "                         \"initialTreatmentDate\": \"20050514\"\r\n"
			+ "                    },\r\n"
			+ "                    \"testResults\": [\r\n"
			+ "                         {\r\n"
			+ "                              \"measurementReferenceIdentificationCode\": \"TR\",\r\n"
			+ "                              \"measurementQualifier\": \"HT\",\r\n"
			+ "                              \"testResults\": \"20050514\"\r\n"
			+ "                         },\r\n"
			+ "                         {\r\n"
			+ "                              \"measurementReferenceIdentificationCode\": \"OG\",\r\n"
			+ "                              \"measurementQualifier\": \"R3\",\r\n"
			+ "                              \"testResults\": \"20050514\"\r\n"
			+ "                         }\r\n"
			+ "                    ],\r\n"
			+ "                    \"contractInformation\": {\r\n"
			+ "                         \"contractTypeCode\": \"02\",\r\n"
			+ "                         \"contractAmount\": \"20050514\",\r\n"
			+ "                         \"contractPercentage\": \"20050514\",\r\n"
			+ "                         \"contractCode\": \"20050514\",\r\n"
			+ "                         \"termsDiscountPercentage\": \"20050514\",\r\n"
			+ "                         \"contractVersionIdentifier\": \"20050514\"\r\n"
			+ "                    },\r\n"
			+ "                    \"serviceLineReferenceInformation\": {\r\n"
			+ "                         \"priorAuthorization\": [\r\n"
			+ "                              {\r\n"
			+ "                                   \"priorAuthorizationOrReferralNumber\": \"20050514\",\r\n"
			+ "                                   \"otherPayerPrimaryIdentifier\": \"20050514\"\r\n"
			+ "                              }\r\n"
			+ "                         ],\r\n"
			+ "                         \"referralNumber\": [\r\n"
			+ "                              \"20050514\",\r\n"
			+ "                              \"20050514\"\r\n"
			+ "                         ],\r\n"
			+ "                         \"repricedLineItemReferenceNumber\": \"20050514\",\r\n"
			+ "                         \"adjustedRepricedLineItemReferenceNumber\": \"20050514\",\r\n"
			+ "                         \"mammographyCertificationNumber\": \"20050514\",\r\n"
			+ "                         \"clinicalLaboratoryImprovementAmendmentNumber\": \"20050514\",\r\n"
			+ "                         \"referringCliaNumber\": \"20050514\",\r\n"
			+ "                         \"immunizationBatchNumber\": \"20050514\"\r\n"
			+ "                    },\r\n"
			+ "                    \"fileInformation\": [\r\n"
			+ "                         \"20050514\",\r\n"
			+ "                         \"20050514\"\r\n"
			+ "                    ],\r\n"
			+ "                    \"purchasedServiceInformation\": {\r\n"
			+ "                         \"purchasedServiceProviderIdentifier\": \"01\",\r\n"
			+ "                         \"purchasedServiceChargeAmount\": \"10\"\r\n"
			+ "                    },\r\n"
			+ "                    \"linePricingRepricingInformation\": {\r\n"
			+ "                         \"pricingMethodologyCode\": \"12\",\r\n"
			+ "                         \"repricedAllowedAmount\": \"1\",\r\n"
			+ "                         \"repricedSavingAmount\": \"20050514\",\r\n"
			+ "                         \"repricingOrganizationIdentifier\": \"20050514\",\r\n"
			+ "                         \"repricingPerDiemOrFlatRateAmoung\": \"20050514\",\r\n"
			+ "                         \"repricedApprovedAmbulatoryPatientGroupCode\": \"20050514\",\r\n"
			+ "                         \"repricedApprovedAmbulatoryPatientGroupAmount\": \"20050514\",\r\n"
			+ "                         \"rejectReasonCode\": \"T1\",\r\n"
			+ "                         \"policyComplianceCode\": \"2\",\r\n"
			+ "                         \"exceptionCode\": \"2\"\r\n"
			+ "                    },\r\n"
			+ "                    \"drugIdentification\": {\r\n"
			+ "                         \"serviceIdQualifier\": \"EO\",\r\n"
			+ "                         \"nationalDrugCode\": \"20050514\",\r\n"
			+ "                         \"nationalDrugUnitCount\": \"20050514\",\r\n"
			+ "                         \"measurementUnitCode\": \"GR\",\r\n"
			+ "                         \"pharmacyPrescriptionNumber\": \"20050514\"\r\n"
			+ "                    },\r\n"
			+ "                    \"renderingProvider\": {\r\n"
			+ "                         \"address\": {\r\n"
			+ "                              \"address2\": \"apt 000\",\r\n"
			+ "                              \"address1\": \"123 address1\",\r\n"
			+ "                              \"city\": \"city1\",\r\n"
			+ "                              \"state\": \"wa\",\r\n"
			+ "                              \"postalCode\": \"981010000\",\r\n"
			+ "                              \"countryCode\": \"20050514\",\r\n"
			+ "                              \"countrySubDivisionCode\": \"20050514\"\r\n"
			+ "                         },\r\n"
			+ "                         \"contactInformation\": {\r\n"
			+ "                              \"name\": \"SUBMITTER CONTACT INFO\",\r\n"
			+ "                              \"phoneNumber\": \"0000000000\",\r\n"
			+ "                              \"faxNumber\": \"0000000000\",\r\n"
			+ "                              \"email\": \"email@email.com\",\r\n"
			+ "                              \"phoneExtension\": \"1234\"\r\n"
			+ "                         },\r\n"
			+ "                         \"secondaryIdentifier\": [\r\n"
			+ "                              {\r\n"
			+ "                                   \"qualifier\": \"20050514\",\r\n"
			+ "                                   \"identifier\": \"20050514\",\r\n"
			+ "                                   \"otherIdentifier\": \"20050514\"\r\n"
			+ "                              },\r\n"
			+ "                              {\r\n"
			+ "                                   \"qualifier\": \"20050514\",\r\n"
			+ "                                   \"identifier\": \"20050514\"\r\n"
			+ "                              }\r\n"
			+ "                         ],\r\n"
			+ "                         \"providerType\": \"BillingProvider\",\r\n"
			+ "                         \"npi\": \"1760854442\",\r\n"
			+ "                         \"ssn\": \"000000000\",\r\n"
			+ "                         \"employerId\": \"123456789\",\r\n"
			+ "                         \"commercialNumber\": \"20050514\",\r\n"
			+ "                         \"locationNumber\": \"20050514\",\r\n"
			+ "                         \"payerIdentificationNumber\": \"20050514\",\r\n"
			+ "                         \"employerIdentificationNumber\": \"20050514\",\r\n"
			+ "                         \"claimOfficeNumber\": \"20050514\",\r\n"
			+ "                         \"stateLicenseNumber\": \"0000000\",\r\n"
			+ "                         \"providerUpinNumber\": \"20050514\",\r\n"
			+ "                         \"taxonomyCode\": \"20050514\",\r\n"
			+ "                         \"firstName\": \"johnone\",\r\n"
			+ "                         \"lastName\": \"doeone\",\r\n"
			+ "                         \"organizationName\": \"HAPPY DOCTORS GROUPPRACTICE\",\r\n"
			+ "                         \"middleName\": \"middleone\",\r\n"
			+ "                         \"otherIdentifier\": \"20050514\"\r\n"
			+ "                    },\r\n"
			+ "                    \"purchasedServiceProvider\": {\r\n"
			+ "                         \"address\": {\r\n"
			+ "                              \"address1\": \"123 address1\",\r\n"
			+ "                              \"address2\": \"apt 000\",\r\n"
			+ "                              \"city\": \"city1\",\r\n"
			+ "                              \"state\": \"wa\",\r\n"
			+ "                              \"postalCode\": \"981010000\",\r\n"
			+ "                              \"countryCode\": \"20050514\",\r\n"
			+ "                              \"countrySubDivisionCode\": \"20050514\"\r\n"
			+ "                         },\r\n"
			+ "                         \"contactInformation\": {\r\n"
			+ "                              \"name\": \"SUBMITTER CONTACT INFO\",\r\n"
			+ "                              \"phoneNumber\": \"0000000000\",\r\n"
			+ "                              \"faxNumber\": \"0000000000\",\r\n"
			+ "                              \"email\": \"email@email.com\",\r\n"
			+ "                              \"phoneExtension\": \"1234\"\r\n"
			+ "                         },\r\n"
			+ "                         \"secondaryIdentifier\": [\r\n"
			+ "                              {\r\n"
			+ "                                   \"qualifier\": \"20050514\",\r\n"
			+ "                                   \"identifier\": \"20050514\",\r\n"
			+ "                                   \"otherIdentifier\": \"20050514\"\r\n"
			+ "                              }\r\n"
			+ "                         ],\r\n"
			+ "                         \"providerType\": \"BillingProvider\",\r\n"
			+ "                         \"npi\": \"1760854442\",\r\n"
			+ "                         \"ssn\": \"000000000\",\r\n"
			+ "                         \"employerId\": \"123456789\",\r\n"
			+ "                         \"commercialNumber\": \"20050514\",\r\n"
			+ "                         \"locationNumber\": \"20050514\",\r\n"
			+ "                         \"payerIdentificationNumber\": \"20050514\",\r\n"
			+ "                         \"employerIdentificationNumber\": \"20050514\",\r\n"
			+ "                         \"claimOfficeNumber\": \"20050514\",\r\n"
			+ "                         \"stateLicenseNumber\": \"0000000\",\r\n"
			+ "                         \"providerUpinNumber\": \"20050514\",\r\n"
			+ "                         \"taxonomyCode\": \"20050514\",\r\n"
			+ "                         \"firstName\": \"johnone\",\r\n"
			+ "                         \"lastName\": \"doeone\",\r\n"
			+ "                         \"middleName\": \"middleone\",\r\n"
			+ "                         \"organizationName\": \"HAPPY DOCTORS GROUPPRACTICE\",\r\n"
			+ "                         \"otherIdentifier\": \"20050514\"\r\n"
			+ "                    },\r\n"
			+ "                    \"serviceFacilityLocation\": {\r\n"
			+ "                         \"address\": {\r\n"
			+ "                              \"address1\": \"123 address1\",\r\n"
			+ "                              \"address2\": \"apt 000\",\r\n"
			+ "                              \"city\": \"city1\",\r\n"
			+ "                              \"state\": \"wa\",\r\n"
			+ "                              \"postalCode\": \"981010000\",\r\n"
			+ "                              \"countryCode\": \"20050514\",\r\n"
			+ "                              \"countrySubDivisionCode\": \"20050514\"\r\n"
			+ "                         },\r\n"
			+ "                         \"secondaryIdentifier\": [\r\n"
			+ "                              {\r\n"
			+ "                                   \"qualifier\": \"LU\",\r\n"
			+ "                                   \"identifier\": \"20050514\",\r\n"
			+ "                                   \"otherIdentifier\": \"20050514\"\r\n"
			+ "                              }\r\n"
			+ "                         ],\r\n"
			+ "                         \"organizationName\": \"HAPPY DOCTORS GROUP\",\r\n"
			+ "                         \"npi\": \"20050514\",\r\n"
			+ "                         \"phoneName\": \"20050514\",\r\n"
			+ "                         \"phoneNumber\": \"20050514\",\r\n"
			+ "                         \"phoneExtension\": \"20050514\"\r\n"
			+ "                    },\r\n"
			+ "                    \"supervisingProvider\": {\r\n"
			+ "                         \"address\": {\r\n"
			+ "                              \"address1\": \"123 address1\",\r\n"
			+ "                              \"address2\": \"apt 000\",\r\n"
			+ "                              \"city\": \"city1\",\r\n"
			+ "                              \"state\": \"wa\",\r\n"
			+ "                              \"postalCode\": \"981010000\",\r\n"
			+ "                              \"countryCode\": \"20050514\",\r\n"
			+ "                              \"countrySubDivisionCode\": \"20050514\"\r\n"
			+ "                         },\r\n"
			+ "                         \"contactInformation\": {\r\n"
			+ "                              \"name\": \"SUBMITTER CONTACT INFO\",\r\n"
			+ "                              \"phoneNumber\": \"0000000000\",\r\n"
			+ "                              \"faxNumber\": \"0000000000\",\r\n"
			+ "                              \"email\": \"email@email.com\",\r\n"
			+ "                              \"phoneExtension\": \"1234\"\r\n"
			+ "                         },\r\n"
			+ "                         \"secondaryIdentifier\": [\r\n"
			+ "                              {\r\n"
			+ "                                   \"qualifier\": \"20050514\",\r\n"
			+ "                                   \"identifier\": \"20050514\"\r\n"
			+ "                              },\r\n"
			+ "                              {\r\n"
			+ "                                   \"qualifier\": \"20050514\",\r\n"
			+ "                                   \"identifier\": \"20050514\"\r\n"
			+ "                              }\r\n"
			+ "                         ],\r\n"
			+ "                         \"providerType\": \"BillingProvider\",\r\n"
			+ "                         \"npi\": \"1760854442\",\r\n"
			+ "                         \"ssn\": \"000000000\",\r\n"
			+ "                         \"employerId\": \"123456789\",\r\n"
			+ "                         \"commercialNumber\": \"20050514\",\r\n"
			+ "                         \"locationNumber\": \"20050514\",\r\n"
			+ "                         \"payerIdentificationNumber\": \"20050514\",\r\n"
			+ "                         \"employerIdentificationNumber\": \"20050514\",\r\n"
			+ "                         \"claimOfficeNumber\": \"20050514\",\r\n"
			+ "                         \"stateLicenseNumber\": \"0000000\",\r\n"
			+ "                         \"providerUpinNumber\": \"20050514\",\r\n"
			+ "                         \"taxonomyCode\": \"20050514\",\r\n"
			+ "                         \"firstName\": \"johnone\",\r\n"
			+ "                         \"lastName\": \"doeone\",\r\n"
			+ "                         \"middleName\": \"middleone\",\r\n"
			+ "                         \"organizationName\": \"HAPPY DOCTORS GROUPPRACTICE\",\r\n"
			+ "                         \"otherIdentifier\": \"20050514\"\r\n"
			+ "                    },\r\n"
			+ "                    \"referringProvider\": {\r\n"
			+ "                         \"address\": {\r\n"
			+ "                              \"address1\": \"123 address1\",\r\n"
			+ "                              \"address2\": \"apt 000\",\r\n"
			+ "                              \"city\": \"city1\",\r\n"
			+ "                              \"state\": \"wa\",\r\n"
			+ "                              \"postalCode\": \"981010000\",\r\n"
			+ "                              \"countryCode\": \"20050514\",\r\n"
			+ "                              \"countrySubDivisionCode\": \"20050514\"\r\n"
			+ "                         },\r\n"
			+ "                         \"contactInformation\": {\r\n"
			+ "                              \"name\": \"SUBMITTER CONTACT INFO\",\r\n"
			+ "                              \"phoneNumber\": \"0000000000\",\r\n"
			+ "                              \"faxNumber\": \"0000000000\",\r\n"
			+ "                              \"email\": \"email@email.com\",\r\n"
			+ "                              \"phoneExtension\": \"1234\"\r\n"
			+ "                         },\r\n"
			+ "                         \"secondaryIdentifier\": [\r\n"
			+ "                              {\r\n"
			+ "                                   \"qualifier\": \"20050514\",\r\n"
			+ "                                   \"otherIdentifier\": \"20050514\",\r\n"
			+ "                                   \"identifier\": \"20050514\"\r\n"
			+ "                              }\r\n"
			+ "                         ],\r\n"
			+ "                         \"providerType\": \"BillingProvider\",\r\n"
			+ "                         \"npi\": \"1760854442\",\r\n"
			+ "                         \"ssn\": \"000000000\",\r\n"
			+ "                         \"employerId\": \"123456789\",\r\n"
			+ "                         \"commercialNumber\": \"20050514\",\r\n"
			+ "                         \"locationNumber\": \"20050514\",\r\n"
			+ "                         \"payerIdentificationNumber\": \"20050514\",\r\n"
			+ "                         \"employerIdentificationNumber\": \"20050514\",\r\n"
			+ "                         \"claimOfficeNumber\": \"20050514\",\r\n"
			+ "                         \"stateLicenseNumber\": \"0000000\",\r\n"
			+ "                         \"providerUpinNumber\": \"20050514\",\r\n"
			+ "                         \"taxonomyCode\": \"20050514\",\r\n"
			+ "                         \"firstName\": \"johnone\",\r\n"
			+ "                         \"lastName\": \"doeone\",\r\n"
			+ "                         \"middleName\": \"middleone\",\r\n"
			+ "                         \"organizationName\": \"HAPPY DOCTORS GROUPPRACTICE\",\r\n"
			+ "                         \"otherIdentifier\": \"20050514\"\r\n"
			+ "                    },\r\n"
			+ "                    \"ambulancePickUpLocation\": {\r\n"
			+ "                         \"address1\": \"123 address1\",\r\n"
			+ "                         \"address2\": \"apt 000\",\r\n"
			+ "                         \"state\": \"wa\",\r\n"
			+ "                         \"city\": \"city1\",\r\n"
			+ "                         \"postalCode\": \"981010000\",\r\n"
			+ "                         \"countryCode\": \"20050514\",\r\n"
			+ "                         \"countrySubDivisionCode\": \"20050514\"\r\n"
			+ "                    },\r\n"
			+ "                    \"ambulanceDropOffLocation\": {\r\n"
			+ "                         \"address1\": \"123 address1\",\r\n"
			+ "                         \"address2\": \"apt 000\",\r\n"
			+ "                         \"city\": \"city1\",\r\n"
			+ "                         \"state\": \"wa\",\r\n"
			+ "                         \"postalCode\": \"981010000\",\r\n"
			+ "                         \"countryCode\": \"20050514\",\r\n"
			+ "                         \"countrySubDivisionCode\": \"20050514\"\r\n"
			+ "                    },\r\n"
			+ "                    \"lineAdjudicationInformation\": [\r\n"
			+ "                         {\r\n"
			+ "                              \"procedureModifier\": [\r\n"
			+ "                                   \"20050514\",\r\n"
			+ "                                   \"20050514\"\r\n"
			+ "                              ],\r\n"
			+ "                              \"otherPayerPrimaryIdentifier\": \"20050514\",\r\n"
			+ "                              \"serviceIdQualifier\": \"HP\",\r\n"
			+ "                              \"serviceLinePaidAmount\": \"20050514\",\r\n"
			+ "                              \"procedureCode\": \"20050514\",\r\n"
			+ "                              \"paidServiceUnitCount\": \"20050514\",\r\n"
			+ "                              \"bundledOrUnbundledLineNumber\": \"20050514\",\r\n"
			+ "                              \"adjudicationOrPaymentDate\": \"20050514\",\r\n"
			+ "                              \"remainingPatientLiability\": \"20050514\"\r\n"
			+ "                         },\r\n"
			+ "                         {\r\n"
			+ "                              \"procedureModifier\": [\r\n"
			+ "                                   \"20050514\",\r\n"
			+ "                                   \"20050514\"\r\n"
			+ "                              ],\r\n"
			+ "                              \"otherPayerPrimaryIdentifier\": \"20050514\",\r\n"
			+ "                              \"serviceLinePaidAmount\": \"20050514\",\r\n"
			+ "                              \"serviceIdQualifier\": \"HP\",\r\n"
			+ "                              \"procedureCode\": \"20050514\",\r\n"
			+ "                              \"paidServiceUnitCount\": \"20050514\",\r\n"
			+ "                              \"bundledOrUnbundledLineNumber\": \"20050514\",\r\n"
			+ "                              \"adjudicationOrPaymentDate\": \"20050514\",\r\n"
			+ "                              \"remainingPatientLiability\": \"20050514\"\r\n"
			+ "                         },\r\n"
			+ "                         {\r\n"
			+ "                              \"otherPayerPrimaryIdentifier\": \"20050514\",\r\n"
			+ "                              \"serviceIdQualifier\": \"ER\",\r\n"
			+ "                              \"serviceLinePaidAmount\": \"20050514\",\r\n"
			+ "                              \"procedureCode\": \"20050514\",\r\n"
			+ "                              \"paidServiceUnitCount\": \"20050514\",\r\n"
			+ "                              \"adjudicationOrPaymentDate\": \"20050514\",\r\n"
			+ "                              \"remainingPatientLiability\": \"20050514\"\r\n"
			+ "                         }\r\n"
			+ "                    ],\r\n"
			+ "                    \"formIdentification\": [\r\n"
			+ "                         {\r\n"
			+ "                              \"supportingDocumentation\": [\r\n"
			+ "                                   {\r\n"
			+ "                                        \"questionNumber\": \"20050514\",\r\n"
			+ "                                        \"questionResponseCode\": \"W\"\r\n"
			+ "                                   },\r\n"
			+ "                                   {\r\n"
			+ "                                        \"questionNumber\": \"20050514\",\r\n"
			+ "                                        \"questionResponseCode\": \"W\"\r\n"
			+ "                                   }\r\n"
			+ "                              ],\r\n"
			+ "                              \"formTypeCode\": \"AS\",\r\n"
			+ "                              \"formIdentifier\": \"20050514\"\r\n"
			+ "                         }\r\n"
			+ "                    ],\r\n"
			+ "                    \"assignedNumber\": \"sdvsdv\",\r\n"
			+ "                    \"serviceDate\": \"20050514\",\r\n"
			+ "                    \"serviceDateEnd\": \"20050514\",\r\n"
			+ "                    \"providerControlNumber\": \"212234321\",\r\n"
			+ "                    \"hospiceEmployeeIndicator\": true,\r\n"
			+ "                    \"ambulancePatientCount\": 20050514,\r\n"
			+ "                    \"obstetricAnesthesiaAdditionalUnits\": 20050514,\r\n"
			+ "                    \"salesTaxAmount\": \"20050514\",\r\n"
			+ "                    \"postageTaxAmount\": \"20050514\",\r\n"
			+ "                    \"additionalNotes\": \"20050514\",\r\n"
			+ "                    \"goalRehabOrDischargePlans\": \"20050514\",\r\n"
			+ "                    \"thirdPartyOrganizationNotes\": \"20050514\"\r\n"
			+ "               }\r\n"
			+ "          ]\r\n"
			+ "			}";

	public static final String AVAILABLE_CUSTOMER_DOCUMENT_URL = "https://sandbox.apigw.changehealthcare.com/medicalnetwork/reports/v2";
	public static final String ATTACHMENTSTAT_HEALTHCHECK_URL = "https://sandbox.apigw.changehealthcare.com/medicalnetwork/attachments/status/v1/healthcheck";
	public static final String ATTACHMENTSTAT_METADATA_URL = "https://sandbox.apigw.changehealthcare.com/medicalnetwork/attachments/status/v1/metadata";
	public static final String ATTACHMENTSTAT_TRACE_URL = "https://sandbox.apigw.changehealthcare.com/medicalnetwork/attachments/status/v1/";
}
